The BioCro C++ Library: /github/workspace/src/R_module_wrapper.cpp File Reference
R_module_wrapper.cpp File Reference
#include <string>
#include <Rinternals.h>
#include <memory>
#include "state_map.h"
#include "R_helper_functions.h"
#include "module_library/module_wrapper_factory.h"
#include "module_wrapper.h"
Functions
void finalize_module_wrapper_pointer (SEXP mw_ptr)
Deletes a module_wrapper_base object that is pointed to by an "R external pointer" object.
SEXP R_module_wrapper_pointer (SEXP module_names)
Creates a vector of "R external pointer" objects that each point to a module_wrapper_base object.
Function Documentation
finalize_module_wrapper_pointer()
void finalize_module_wrapper_pointer (SEXP mw_ptr)
Deletes a module_wrapper_base object that is pointed to by an "R external pointer" object.
See http://www.hep.by/gnu/r-patched/r-exts/R-exts_122.html for more details.
Parameters
[in] m_ptr an "R external pointer" object that points to a module_wrapper_base object
Definition at line 18 of file R_module_wrapper.cpp.
Referenced by R_module_wrapper_pointer().
R_module_wrapper_pointer()
SEXP R_module_wrapper_pointer (SEXP module_names)
Creates a vector of "R external pointer" objects that each point to a module_wrapper_base object.
See http://www.hep.by/gnu/r-patched/r-exts/R-exts_122.html for more details about R external pointers.
When creating an R external pointer using R_MakeExternalPtr(), it is possible to specify tag and prot arguments for identifying the pointer and protecting its memory. However, it is common to bypass both of these arguments by setting them to R_NilValue (the R null pointer). We follow that route here.
Once an R external pointer has been created, it is also possible to specify a "finalizer" function via R_RegisterFinalizerEx(). This function will be called when garbage is collected and should clear the pointer. By setting the onexit argument of R_RegisterFinalizerEx() to be TRUE, we ensure that the pointer will be cleared when its R session closes.
After its creation, the R external pointer takes ownership of the module_wrapper_base object (in the sense that it will ensure that the module_wrapper_base object is deleted when the pointer is destroyed), so it is critical for the std::unique_ptr to relinquish control via std::unique_ptr::release() rather than std::unique_ptr::get(). Memory access problems will occur otherwise, causing R to suddenly crash.
The output from this function can be converted into a std::vector of module_wrapper_base pointers for use in C/C++ code using the mw_vector_from_list() function.
Parameters
[in] module_names The names of the modules for which module_wrapper_base objects should be created
Returns
A vector of "R external pointer" objects
Definition at line 63 of file R_module_wrapper.cpp.
References finalize_module_wrapper_pointer(), and make_vector().