The BioCro C++ Library: parameter_list Struct Reference
parameter_list Struct Reference
#include <parameters.h>
Public Types
typedef std::pair< std::string, parameter > parameter_entry
typedef std::unordered_map< std::string, parameter > parameter_entries
Public Member Functions
parameter_list (parameter_entries const &l=parameter_entries())
parameter_list (std::initializer_list< parameter_entries::value_type > const &l)
void add (parameter_entry const &entry)
void add (std::string const &s, char const delim, bool const trim)
void add (parameter_entries const &l)
Public Attributes
parameter_entries _parameter_list
Detailed Description
Definition at line 15 of file parameters.h.
Member Typedef Documentation
parameter_entries
typedef std::unordered_map<std::string, parameter> parameter_entries
Definition at line 17 of file parameters.h.
parameter_entry
typedef std::pair<std::string, parameter> parameter_entry
Definition at line 16 of file parameters.h.
Constructor & Destructor Documentation
parameter_list() [1/2]
parameter_list (parameter_entries const & l = parameter_entries()) inline
Definition at line 19 of file parameters.h.
parameter_list() [2/2]
parameter_list (std::initializer_list< parameter_entries::value_type > const & l) inline
Definition at line 20 of file parameters.h.
Member Function Documentation
add() [1/3]
void add (parameter_entries const & l) inline
Definition at line 33 of file parameters.h.
References add().
add() [2/3]
void add (parameter_entry const & entry) inline
Definition at line 28 of file parameters.h.
References _parameter_list.
Referenced by add().
add() [3/3]
void add (std::string const & s, char const delim, bool const trim) inline
Definition at line 40 of file parameters.h.
References add().
Member Data Documentation
_parameter_list
parameter_entries _parameter_list
Definition at line 25 of file parameters.h.
Referenced by add().
The documentation for this struct was generated from the following file:
/github/workspace/src/parameters.h