The BioCro C++ Library: /github/workspace/src/module_library/c3photo.hpp File Reference
c3photo.hpp File Reference
Classes
struct c3_str
Functions
struct c3_str c3photoC (double Qp, double Tleaf, double RH, double Vcmax0, double Jmax0, double tpu_rate_max, double Rd0, double bb0, double bb1, double Gs_min, double Ca, double AP, double O2, double theta, double StomWS, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation)
struct c3_str c3photoCdb (double Qp, double Tleaf, double RH, double Vcmax0, double Jmax0, double tpu_rate_max, double Rd0, double bb0, double bb1, double Gs_min, double Ca, double AP, double O2, double theta, double StomWS, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation)
double solc (double LeafT)
double solo (double LeafT)
Function Documentation
c3photoC()
struct c3_str c3photoC (double Qp, double Tleaf, double RH, double Vcmax0, double Jmax0, double tpu_rate_max, double Rd0, double bb0, double bb1, double Gs_min, double Ca, double AP, double O2, double theta, double StomWS, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation)
Definition at line 21 of file c3photo.cpp.
Referenced by c3CanAC(), c3_assimilation::do_operation(), and c3_leaf_photosynthesis::do_operation().
c3photoCdb()
struct c3_str c3photoCdb (double Qp, double Tleaf, double RH, double Vcmax0, double Jmax0, double tpu_rate_max, double Rd0, double bb0, double bb1, double Gs_min, double Ca, double AP, double O2, double theta, double StomWS, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation)
solc()
double solc (double LeafT)
Definition at line 198 of file c3photo.cpp.
solo()
double solo (double LeafT)
Definition at line 211 of file c3photo.cpp.