The BioCro C++ Library: /github/workspace/src/module_library/c4photo.cpp File Reference
c4photo.cpp File Reference
#include <cmath>
#include "ball_berry.hpp"
#include "c4photo.h"
Functions
struct c4_str c4photoC (double Qp, double leaf_temperature, double relative_humidity, double vmax, double alpha, double kparm, double theta, double beta, double Rd, double bb0, double bb1, double Gs_min, double StomaWS, double Ca, double atmospheric_pressure, int water_stress_approach, double upperT, double lowerT)
Function Documentation
c4photoC()
struct c4_str c4photoC (double Qp, double leaf_temperature, double relative_humidity, double vmax, double alpha, double kparm, double theta, double beta, double Rd, double bb0, double bb1, double Gs_min, double StomaWS, double Ca, double atmospheric_pressure, int water_stress_approach, double upperT, double lowerT)
Definition at line 1 of file c4photo.cpp.
References c4_str::Assim, ball_berry(), c4_str::Ci, and c4_str::Gs.
Referenced by CanAC(), c4_assimilation::do_operation(), and c4_leaf_photosynthesis::do_operation().