var hierarchy =
[
    [ "c3_str", "structc3__str.html", null ],
    [ "c4_str", "structc4__str.html", null ],
    [ "Can_Str", "struct_can___str.html", null ],
    [ "collatz_result", "structcollatz__result.html", null ],
    [ "crop_phenology", "structcrop__phenology.html", null ],
    [ "dbp_str", "structdbp__str.html", null ],
    [ "differential_module", null, [
      [ "aba_decay", "classaba__decay.html", null ],
      [ "bucket_soil_drainage", "classbucket__soil__drainage.html", null ],
      [ "development_index", "classdevelopment__index.html", null ],
      [ "empty_senescence", "classempty__senescence.html", null ],
      [ "example_model_partitioning", "classexample__model__partitioning.html", null ],
      [ "grimm_soybean_flowering", "classgrimm__soybean__flowering.html", null ],
      [ "harmonic_oscillator", "classharmonic__oscillator.html", null ],
      [ "magic_clock", "classmagic__clock.html", null ],
      [ "night_and_day_trackers", "classnight__and__day__trackers.html", null ],
      [ "nr_ex", "classnr__ex.html", null ],
      [ "one_layer_soil_profile", "classone__layer__soil__profile.html", null ],
      [ "one_layer_soil_profile_derivatives", "classone__layer__soil__profile__derivatives.html", null ],
      [ "partitioning_growth", "classpartitioning__growth.html", null ],
      [ "phase_clock", "classphase__clock.html", null ],
      [ "poincare_clock", "classpoincare__clock.html", null ],
      [ "pokhilko_circadian_clock", "classpokhilko__circadian__clock.html", null ],
      [ "senescence_logistic", "classsenescence__logistic.html", null ],
      [ "song_flowering", "classsong__flowering.html", null ],
      [ "thermal_time_and_frost_senescence", "classthermal__time__and__frost__senescence.html", null ],
      [ "thermal_time_beta", "classthermal__time__beta.html", null ],
      [ "thermal_time_bilinear", "classthermal__time__bilinear.html", null ],
      [ "thermal_time_linear", "classthermal__time__linear.html", null ],
      [ "thermal_time_linear_extended", "classthermal__time__linear__extended.html", null ],
      [ "thermal_time_senescence", "classthermal__time__senescence.html", null ],
      [ "thermal_time_trilinear", "classthermal__time__trilinear.html", null ],
      [ "two_layer_soil_profile", "classtwo__layer__soil__profile.html", null ]
    ] ],
    [ "direct_module", null, [
      [ "FvCB", "class_fv_c_b.html", null ],
      [ "Module_1", "class_module__1.html", null ],
      [ "Module_2", "class_module__2.html", null ],
      [ "Module_3", "class_module__3.html", null ],
      [ "ball_berry_module", "classball__berry__module.html", null ],
      [ "biomass_leaf_n_limitation", "classbiomass__leaf__n__limitation.html", null ],
      [ "buck_swvp", "classbuck__swvp.html", null ],
      [ "c3_assimilation", "classc3__assimilation.html", null ],
      [ "c3_canopy", "classc3__canopy.html", null ],
      [ "c3_leaf_photosynthesis", "classc3__leaf__photosynthesis.html", null ],
      [ "c4_assimilation", "classc4__assimilation.html", null ],
      [ "c4_canopy", "classc4__canopy.html", null ],
      [ "c4_leaf_photosynthesis", "classc4__leaf__photosynthesis.html", null ],
      [ "example_model_mass_gain", "classexample__model__mass__gain.html", null ],
      [ "fake_solar", "classfake__solar.html", null ],
      [ "golden_ratio_hyperbola", "classgolden__ratio__hyperbola.html", null ],
      [ "grimm_soybean_flowering_calculator", "classgrimm__soybean__flowering__calculator.html", null ],
      [ "harmonic_energy", "classharmonic__energy.html", null ],
      [ "hyperbola_2d", "classhyperbola__2d.html", null ],
      [ "incident_shortwave_from_ground_par", "classincident__shortwave__from__ground__par.html", null ],
      [ "leaf_gbw_nikolov", "classleaf__gbw__nikolov.html", null ],
      [ "leaf_gbw_thornley", "classleaf__gbw__thornley.html", null ],
      [ "leaf_shape_factor", "classleaf__shape__factor.html", null ],
      [ "leaf_water_stress_exponential", "classleaf__water__stress__exponential.html", null ],
      [ "light_from_solar", "classlight__from__solar.html", null ],
      [ "linear_vmax_from_leaf_n", "classlinear__vmax__from__leaf__n.html", null ],
      [ "multilayer_canopy_integrator", "classmultilayer__canopy__integrator.html", [
        [ "ten_layer_canopy_integrator", "classten__layer__canopy__integrator.html", null ]
      ] ],
      [ "multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >", "classmultilayer__canopy__photosynthesis.html", [
        [ "ten_layer_c3_canopy", "classten__layer__c3__canopy.html", null ],
        [ "ten_layer_c4_canopy", "classten__layer__c4__canopy.html", null ],
        [ "ten_layer_rue_canopy", "classten__layer__rue__canopy.html", null ]
      ] ],
      [ "multilayer_canopy_properties", "classmultilayer__canopy__properties.html", [
        [ "ten_layer_canopy_properties", "classten__layer__canopy__properties.html", null ]
      ] ],
      [ "no_leaf_resp_neg_assim_partitioning_growth_calculator", "classno__leaf__resp__neg__assim__partitioning__growth__calculator.html", null ],
      [ "no_leaf_resp_partitioning_growth_calculator", "classno__leaf__resp__partitioning__growth__calculator.html", null ],
      [ "oscillator_clock_calculator", "classoscillator__clock__calculator.html", null ],
      [ "parameter_calculator", "classparameter__calculator.html", null ],
      [ "partitioning_coefficient_logistic", "classpartitioning__coefficient__logistic.html", null ],
      [ "partitioning_coefficient_selector", "classpartitioning__coefficient__selector.html", null ],
      [ "partitioning_growth_calculator", "classpartitioning__growth__calculator.html", null ],
      [ "penman_monteith_leaf_temperature", "classpenman__monteith__leaf__temperature.html", null ],
      [ "penman_monteith_transpiration", "classpenman__monteith__transpiration.html", null ],
      [ "priestley_transpiration", "classpriestley__transpiration.html", null ],
      [ "rasmussen_specific_heat", "classrasmussen__specific__heat.html", null ],
      [ "rh_to_mole_fraction", "classrh__to__mole__fraction.html", null ],
      [ "rue_leaf_photosynthesis", "classrue__leaf__photosynthesis.html", null ],
      [ "senescence_coefficient_logistic", "classsenescence__coefficient__logistic.html", null ],
      [ "shortwave_atmospheric_scattering", "classshortwave__atmospheric__scattering.html", null ],
      [ "soil_evaporation", "classsoil__evaporation.html", null ],
      [ "soil_type_selector", "classsoil__type__selector.html", null ],
      [ "solar_position_michalsky", "classsolar__position__michalsky.html", null ],
      [ "soybean_development_rate_calculator", "classsoybean__development__rate__calculator.html", null ],
      [ "stomata_water_stress_exponential", "classstomata__water__stress__exponential.html", null ],
      [ "stomata_water_stress_linear", "classstomata__water__stress__linear.html", null ],
      [ "stomata_water_stress_linear_and_aba_response", "classstomata__water__stress__linear__and__aba__response.html", null ],
      [ "stomata_water_stress_sigmoid", "classstomata__water__stress__sigmoid.html", null ],
      [ "thermal_time_development_rate_calculator", "classthermal__time__development__rate__calculator.html", null ],
      [ "total_biomass", "classtotal__biomass.html", null ],
      [ "water_vapor_properties_from_air_temperature", "classwater__vapor__properties__from__air__temperature.html", null ]
    ] ],
    [ "ET_Str", "struct_e_t___str.html", null ],
    [ "frostParms", "structfrost_parms.html", null ],
    [ "Light_model", "struct_light__model.html", null ],
    [ "Light_profile", "struct_light__profile.html", null ],
    [ "crop_phenology::minerals1", "structcrop__phenology_1_1minerals1.html", null ],
    [ "module_wrapper_factory", "classmodule__wrapper__factory.html", null ],
    [ "nitroParms", "structnitro_parms.html", null ],
    [ "rd_str", "structrd__str.html", null ],
    [ "rue_str", "structrue__str.html", null ],
    [ "seqRD_str", "structseq_r_d__str.html", null ],
    [ "soilML_str", "structsoil_m_l__str.html", null ],
    [ "soilText_str", "structsoil_text__str.html", null ],
    [ "ws_str", "structws__str.html", null ]
];