The BioCro C++ Library: /github/workspace/src/module_library/c3EvapoTrans.cpp File Reference
c3EvapoTrans.cpp File Reference
#include <cmath>
#include <stdexcept>
#include "c3photo.hpp"
#include "AuxBioCro.h"
#include "BioCro.h"
#include "../constants.h"
Functions
struct ET_Str c3EvapoTrans (double absorbed_shortwave_radiation, double air_temperature, double RH, double WindSpeed, double CanopyHeight, double specific_heat_of_air, double stomatal_conductance, double minimum_gbw, double WindSpeedHeight)
Function Documentation
c3EvapoTrans()
struct ET_Str c3EvapoTrans (double absorbed_shortwave_radiation, double air_temperature, double RH, double WindSpeed, double CanopyHeight, double specific_heat_of_air, double stomatal_conductance, double minimum_gbw, double WindSpeedHeight)
/src/c3EvapoTrans.c by Fernando Ezequiel Miguez Copyright (C) 2010
Part of the code here (sunML, EvapoTrans, SoilEvapo, TempTo and the *prof functions) are based on code in WIMOVAC. WIMOVAC is copyright of Stephen Long and Stephen Humphries. Documentation for WIMOVAC can be found at http://www.life.illinois.edu/plantbio/wimovac/ (checked 02-13-2010)
Many of these functions come from Chapter 14 of Thornley and Johnson (1990).
Thornley, J.H.M. and Johnson, I.R. (1990) Plant and Crop Modelling. A Mathematical Approach to Plant and Crop Physiology.
Definition at line 1 of file c3EvapoTrans.cpp.
References ET_Str::boundary_layer_conductance, ET_Str::Deltat, ET_Str::EPenman, ET_Str::EPriestly, leaf_boundary_layer_conductance_thornley(), saturation_vapor_pressure(), TempToDdryA(), TempToLHV(), TempToSFS(), and ET_Str::TransR.
Referenced by c3CanAC(), c3_leaf_photosynthesis::do_operation(), and rue_leaf_photosynthesis::do_operation().