The BioCro C++ Library: multilayer_canopy_properties Class Reference
multilayer_canopy_properties Class Reference
Calculates environmental properties for sunlit and shaded leaves in each layer of a multilayer canopy, mostly using functions found in AuxBioCro.cpp.
#include <multilayer_canopy_properties.h>
Public Member Functions
multilayer_canopy_properties (int const &nlayers, state_map const &input_quantities, state_map *output_quantities)
Protected Member Functions
void run () const
Static Protected Member Functions
static string_vector get_inputs (int nlayers)
Define all inputs required by the module.
static string_vector define_leaf_classes ()
Define the different leaf classes included by the module.
static string_vector define_multiclass_multilayer_outputs ()
Define all outputs that have different values for each leaf class and layer.
static string_vector define_pure_multilayer_outputs ()
Define all outputs that have different values for each layer, not including outputs that also depend on leaf class.
static string_vector get_outputs (int nlayers)
Define all output names by appending leaf class prefixes and layer number suffixes. Here we should make use of the define_XXX functions to reduce code duplication.
Private Attributes
int const nlayers
double const & par_incident_direct
double const & par_incident_diffuse
double const & absorptivity_par
double const & lai
double const & cosine_zenith_angle
double const & kd
double const & chil
double const & heightf
double const & rh
double const & windspeed
double const & LeafN
double const & kpLN
double const & lnfun
double const & par_energy_content
double const & par_energy_fraction
double const & leaf_transmittance
double const & leaf_reflectance
std::vector< double * > const sunlit_fraction_ops
std::vector< double * > const sunlit_incident_ppfd_ops
std::vector< double * > const sunlit_absorbed_shortwave_ops
std::vector< double * > const shaded_fraction_ops
std::vector< double * > const shaded_incident_ppfd_ops
std::vector< double * > const shaded_absorbed_shortwave_ops
std::vector< double * > const average_incident_ppfd_ops
std::vector< double * > const average_absorbed_shortwave_ops
std::vector< double * > const incident_ppfd_scattered_ops
std::vector< double * > const height_ops
std::vector< double * > const rh_ops
std::vector< double * > const windspeed_ops
std::vector< double * > const LeafN_ops
Detailed Description
Calculates environmental properties for sunlit and shaded leaves in each layer of a multilayer canopy, mostly using functions found in AuxBioCro.cpp.
In general, a canopy can be divided into different layers and leaf classes, which could be based on factors such as angle or age. Here we only consider sunlit and shaded leaves as separate classes. These leaf classes must be specified by the define_leaf_classes() member function.
Throughout the canopy, some calculated properties only vary across the layers (such as air temperature), while others also depend on the leaf class (such as incident photosynthetically active photon flux density). The names of these output quantities are formed from a base name (e.g. incident_ppfd), a prefix that indicates the leaf class (e.g. sunlit_), and a suffix that indicates the layer number (e.g. _layer_0).
For compatibility with the multilayer_canopy_photosynthesis module, the outputs of this module must be split into categories according to their dependence on canopy layer and/or leaf class, and the base names for the quantities of each type must be specified:
multiclass_multilayer outputs: these outputs are different for each leaf class and canopy layer and should be specified by the define_multiclass_multilayer_outputs() function.
pure_multilayer outputs: these outputs are different for each canopy layer but not for each leaf class and should be specified by the define_pure_multilayer_outputs() function.
other outputs: these outputs do not depend on the leaf class or canopy layer and do not need to be specified in a special way (there are currently no outputs of this type)
The base names for the multiclass_multilayer and pure_multilayer outputs will be used by the multilayer_canopy_photosynthesis module to correctly pass these quantities to a leaf photosynthesis module that represents one leaf type (e.g. sunlit leaves in layer 1).
Note that this module has a non-standard constructor, so it cannot be created using the module_wrapper_factory. Rather, it is expected that directly-usable classes will be derived from this class.
Definition at line 53 of file multilayer_canopy_properties.h.
Constructor & Destructor Documentation
multilayer_canopy_properties()
multilayer_canopy_properties (int const & nlayers, state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 56 of file multilayer_canopy_properties.h.
Member Function Documentation
define_leaf_classes()
string_vector define_leaf_classes () static protected
Define the different leaf classes included by the module.
Definition at line 34 of file multilayer_canopy_properties.cpp.
Referenced by ten_layer_canopy_properties::define_leaf_classes(), and get_outputs().
define_multiclass_multilayer_outputs()
string_vector define_multiclass_multilayer_outputs () static protected
Define all outputs that have different values for each leaf class and layer.
Definition at line 46 of file multilayer_canopy_properties.cpp.
Referenced by ten_layer_canopy_properties::define_multiclass_multilayer_outputs(), and get_outputs().
define_pure_multilayer_outputs()
string_vector define_pure_multilayer_outputs () static protected
Define all outputs that have different values for each layer, not including outputs that also depend on leaf class.
Definition at line 59 of file multilayer_canopy_properties.cpp.
Referenced by ten_layer_canopy_properties::define_pure_multilayer_outputs(), and get_outputs().
get_inputs()
string_vector get_inputs (int nlayers) static protected
Define all inputs required by the module.
Definition at line 8 of file multilayer_canopy_properties.cpp.
Referenced by ten_layer_canopy_properties::get_inputs().
get_outputs()
string_vector get_outputs (int nlayers) static protected
Define all output names by appending leaf class prefixes and layer number suffixes. Here we should make use of the define_XXX functions to reduce code duplication.
Definition at line 77 of file multilayer_canopy_properties.cpp.
References define_leaf_classes(), define_multiclass_multilayer_outputs(), define_pure_multilayer_outputs(), and nlayers.
Referenced by ten_layer_canopy_properties::get_outputs().
run()
void run () const protected
Definition at line 94 of file multilayer_canopy_properties.cpp.
References absorptivity_par, Light_profile::average_absorbed_shortwave, average_absorbed_shortwave_ops, Light_profile::average_incident_ppfd, average_incident_ppfd_ops, chil, cosine_zenith_angle, Light_profile::height, height_ops, heightf, Light_profile::incident_ppfd_scattered, incident_ppfd_scattered_ops, kd, kpLN, lai, leaf_reflectance, leaf_transmittance, LeafN, LeafN_ops, lnfun, LNprof(), nlayers, par_energy_content, par_energy_fraction, par_incident_diffuse, par_incident_direct, rh, rh_ops, RHprof(), Light_profile::shaded_absorbed_shortwave, shaded_absorbed_shortwave_ops, Light_profile::shaded_fraction, shaded_fraction_ops, Light_profile::shaded_incident_ppfd, shaded_incident_ppfd_ops, Light_profile::sunlit_absorbed_shortwave, sunlit_absorbed_shortwave_ops, Light_profile::sunlit_fraction, sunlit_fraction_ops, Light_profile::sunlit_incident_ppfd, sunlit_incident_ppfd_ops, sunML(), WINDprof(), windspeed, and windspeed_ops.
Referenced by ten_layer_canopy_properties::do_operation().
Member Data Documentation
absorptivity_par
double const& absorptivity_par private
Definition at line 108 of file multilayer_canopy_properties.h.
Referenced by run().
average_absorbed_shortwave_ops
std::vector<double*> const average_absorbed_shortwave_ops private
Definition at line 132 of file multilayer_canopy_properties.h.
Referenced by run().
average_incident_ppfd_ops
std::vector<double*> const average_incident_ppfd_ops private
Definition at line 131 of file multilayer_canopy_properties.h.
Referenced by run().
chil
double const& chil private
Definition at line 112 of file multilayer_canopy_properties.h.
Referenced by run().
cosine_zenith_angle
double const& cosine_zenith_angle private
Definition at line 110 of file multilayer_canopy_properties.h.
Referenced by run().
height_ops
std::vector<double*> const height_ops private
Definition at line 134 of file multilayer_canopy_properties.h.
Referenced by run().
heightf
double const& heightf private
Definition at line 113 of file multilayer_canopy_properties.h.
Referenced by run().
incident_ppfd_scattered_ops
std::vector<double*> const incident_ppfd_scattered_ops private
Definition at line 133 of file multilayer_canopy_properties.h.
Referenced by run().
kd
double const& kd private
Definition at line 111 of file multilayer_canopy_properties.h.
Referenced by run().
kpLN
double const& kpLN private
Definition at line 117 of file multilayer_canopy_properties.h.
Referenced by run().
lai
double const& lai private
Definition at line 109 of file multilayer_canopy_properties.h.
Referenced by run().
leaf_reflectance
double const& leaf_reflectance private
Definition at line 122 of file multilayer_canopy_properties.h.
Referenced by run().
leaf_transmittance
double const& leaf_transmittance private
Definition at line 121 of file multilayer_canopy_properties.h.
Referenced by run().
LeafN
double const& LeafN private
Definition at line 116 of file multilayer_canopy_properties.h.
Referenced by run().
LeafN_ops
std::vector<double*> const LeafN_ops private
Definition at line 137 of file multilayer_canopy_properties.h.
Referenced by run().
lnfun
double const& lnfun private
Definition at line 118 of file multilayer_canopy_properties.h.
Referenced by run().
nlayers
int const nlayers private
Definition at line 103 of file multilayer_canopy_properties.h.
Referenced by get_outputs(), and run().
par_energy_content
double const& par_energy_content private
Definition at line 119 of file multilayer_canopy_properties.h.
Referenced by run().
par_energy_fraction
double const& par_energy_fraction private
Definition at line 120 of file multilayer_canopy_properties.h.
Referenced by run().
par_incident_diffuse
double const& par_incident_diffuse private
Definition at line 107 of file multilayer_canopy_properties.h.
Referenced by run().
par_incident_direct
double const& par_incident_direct private
Definition at line 106 of file multilayer_canopy_properties.h.
Referenced by run().
rh
double const& rh private
Definition at line 114 of file multilayer_canopy_properties.h.
Referenced by run().
rh_ops
std::vector<double*> const rh_ops private
Definition at line 135 of file multilayer_canopy_properties.h.
Referenced by run().
shaded_absorbed_shortwave_ops
std::vector<double*> const shaded_absorbed_shortwave_ops private
Definition at line 130 of file multilayer_canopy_properties.h.
Referenced by run().
shaded_fraction_ops
std::vector<double*> const shaded_fraction_ops private
Definition at line 128 of file multilayer_canopy_properties.h.
Referenced by run().
shaded_incident_ppfd_ops
std::vector<double*> const shaded_incident_ppfd_ops private
Definition at line 129 of file multilayer_canopy_properties.h.
Referenced by run().
sunlit_absorbed_shortwave_ops
std::vector<double*> const sunlit_absorbed_shortwave_ops private
Definition at line 127 of file multilayer_canopy_properties.h.
Referenced by run().
sunlit_fraction_ops
std::vector<double*> const sunlit_fraction_ops private
Definition at line 125 of file multilayer_canopy_properties.h.
Referenced by run().
sunlit_incident_ppfd_ops
std::vector<double*> const sunlit_incident_ppfd_ops private
Definition at line 126 of file multilayer_canopy_properties.h.
Referenced by run().
windspeed
double const& windspeed private
Definition at line 115 of file multilayer_canopy_properties.h.
Referenced by run().
windspeed_ops
std::vector<double*> const windspeed_ops private
Definition at line 136 of file multilayer_canopy_properties.h.
Referenced by run().
The documentation for this class was generated from the following files:
/github/workspace/src/module_library/multilayer_canopy_properties.h
/github/workspace/src/module_library/multilayer_canopy_properties.cpp