The BioCro C++ Library: biocro_simulation Class Reference
biocro_simulation Class Reference
#include <biocro_simulation.h>
Public Member Functions
biocro_simulation (std::unordered_map< std::string, double > const &initial_values, std::unordered_map< std::string, double > const &parameters, std::unordered_map< std::string, std::vector< double >> const &drivers, std::vector< std::string > const &direct_module_names, std::vector< std::string > const &differential_module_names, std::string ode_solver_name, double output_step_size, double adaptive_rel_error_tol, double adaptive_abs_error_tol, int adaptive_max_steps)
std::unordered_map< std::string, std::vector< double > > run_simulation ()
std::string generate_report () const
Private Attributes
std::shared_ptr< dynamical_system > sys
std::unique_ptr< ode_solver > system_solver
Detailed Description
Definition at line 11 of file biocro_simulation.h.
Constructor & Destructor Documentation
biocro_simulation()
biocro_simulation (std::unordered_map< std::string, double > const & initial_values, std::unordered_map< std::string, double > const & parameters, std::unordered_map< std::string, std::vector< double >> const & drivers, std::vector< std::string > const & direct_module_names, std::vector< std::string > const & differential_module_names, std::string ode_solver_name, double output_step_size, double adaptive_rel_error_tol, double adaptive_abs_error_tol, int adaptive_max_steps) inline
Definition at line 14 of file biocro_simulation.h.
References ode_solver_factory::create(), parameters, sys, and system_solver.
Member Function Documentation
generate_report()
std::string generate_report () const inline
Definition at line 46 of file biocro_simulation.h.
References sys, and system_solver.
Referenced by R_run_biocro().
run_simulation()
std::unordered_map<std::string, std::vector<double> > run_simulation () inline
Definition at line 42 of file biocro_simulation.h.
References sys, and system_solver.
Referenced by R_run_biocro().
Member Data Documentation
sys
std::shared_ptr<dynamical_system> sys private
Definition at line 62 of file biocro_simulation.h.
Referenced by biocro_simulation(), generate_report(), and run_simulation().
system_solver
std::unique_ptr<ode_solver> system_solver private
Definition at line 63 of file biocro_simulation.h.
Referenced by biocro_simulation(), generate_report(), and run_simulation().
The documentation for this class was generated from the following file:
/github/workspace/src/biocro_simulation.h