The BioCro C++ Library: dynamical_system Class Reference
dynamical_system Class Reference
Defines a dynamical system which can be solved using an ode_solver.
#include <dynamical_system.h>
Public Member Functions
dynamical_system (state_map const &init_values, state_map const &params, state_vector_map const &drivers, string_vector const &dir_module_names, string_vector const &differential_module_names)
size_t get_ntimes () const
bool requires_euler_ode_solver () const
template<typename vector_type >
void get_differential_quantities (vector_type &x) const
Updates a vector with the current values of all the differential quantities.
template<typename vector_type , typename time_type >
void update_all_quantities (const vector_type &x, const time_type &t)
Updates all quantities in the internally stored map (including ones calculated by direct modules) based on supplied values for the differential quantities and the time.
template<typename vector_type , typename time_type >
void calculate_derivative (const vector_type &x, vector_type &dxdt, const time_type &t)
Calculates derivatives for each of the differential quantities based on supplied values for the differential quantities and the time. The function signature is set by the boost::odeint library.
vector< const double * > get_quantity_access_ptrs (string_vector quantity_names) const
Returns pointers that can be used to access quantity values from the dynamical_system's central map of quantities.
string_vector get_differential_quantity_names () const
string_vector get_output_quantity_names () const
Returns a vector of the names of all quantities that may change throughout a simulation.
int get_ncalls () const
void reset_ncalls ()
string generate_startup_report () const
string generate_usage_report () const
void reset ()
Resets all internally stored quantities back to their original values.
Private Member Functions
void update_drivers (double time_indx)
Updates values of the drivers in the internally stored quantity map to match their values in the internally stored drivers table at time time_index; values of the drivers at non-integer values of time_index are determined using linear interpolation.
template<typename time_type >
void update_drivers (time_type time_indx)
Updates values of the drivers in the internally stored quantity map to match their values in the internally stored drivers table at time time_index, which should be a discrete index such as an int or size_t.
template<class vector_type >
void update_differential_quantities (vector_type const &new_values)
Updates the system's internally stored values for the differential quantities to the ones in new_values.
template<class vector_type >
void run_differential_modules (vector_type &derivs)
Calculates a derivative from the internally stored quantity map by running all the differential modules.
Private Attributes
const state_map initial_values
const state_map parameters
const state_vector_map drivers
string_vector direct_module_names
const string_vector differential_module_names
state_map all_quantities
state_map differential_quantity_derivatives
module_vector direct_modules
module_vector differential_modules
double * timestep_ptr
vector< pair< double *, const double * > > differential_quantity_ptr_pairs
vector< pair< double *, const vector< double > * > > driver_quantity_ptr_pairs
int ncalls = 0
string startup_message
Detailed Description
Defines a dynamical system which can be solved using an ode_solver.
A dynamical system requires three elements:
A state space, which may generally be thought of as consisting of one or more quantities; here we use the term quantity to refer to a named variable that represents some particular attribute of the state.
An independent quantity upon which the value of the state depends, which is typically taken to be the time.
An evolution rule which describes how to determine the value of the state at a future time given its value at the current time.
This class (together with a differential equation solver) represents a dynamical system. It defines the following:
The quantities that comprise the state. These are determined from the parameters, drivers, direct modules, and differential modules.
The independent quantity. This is assumed to be time.
The equations required to calculate the values of the parameters, drivers, and direct quantities (which are all elements of the state), given values of the differential quantities (another subset of the state) and the time. The equations for the parameters set them equal to constants. The equations for the drivers are determined by interpolating the supplied discrete values. The equations for the direct quantities are supplied by the direct modules.
The equations required to calculate the derivatives of the differential quantities, given the values of the state and the time. These equations are supplied by the differential modules.
The initial values of the differential quantities.
To fully define the evolution rule, it is also necessary to supply a differential equation solver in addition to the equations mentioned above. Such solvers are provided as another class: the ode_solver.
One key property of this class is its private data member all_quantities. This state_map represents the current state of a dynamical system, i.e., it specifies the names and values of all quantities that comprise the state. When a dynamical_system object's direct modules are run, they read quantity values from all_quantities and store calculated quantity values in it; when a dynamical_system object's differential modules are run, they also read quantity values from all_quantities. In that sense, it is a sort of "central clearing house" for quantities. It is sometimes referred to as the "internally stored quantity map" or "internally stored map." The individual quantities that comprise all_quantities are sometimes referred to as "internally stored quantities," and their values may be called "internally stored quantity values."
In addition to the all_quantities data member, there is a separate private data member for storing the outputs from the differential modules; this state_map is called differential_quantity_derivatives. This member is sometimes also referred to as the "internally stored map," and it should be clear from context that derivatives of quantity values, rather than quantity values themselves, are being referenced.
Public methods are provided that allow access to the values or names of subsets of all_quantities and differential_quantity_derivatives:
get_differential_quantity_names returns the names of the differential quantities
get_differential_quantities returns the values of the differential quantities
calculate_derivative calculates the derivatives of each of the differential quantities given values for the time and the differential quantities
get_output_quantity_names returns the names of all quantities that are expected to change throughout a simulation, i.e., the drivers, direct quantities, and differential quantities (but not the parameters)
get_quantity_access_ptrs returns pointers to elements of all_quantities that correspond to quantity names that are supplied in the input argument
update_all_quantities determines the values of all state quantities from input values of time and the differential quantities; this function modifies all_quantities but has no return value
reset returns all quantities to their initial values, as if the dynamical_system object had just been created; this may be helpful if an object is to be reused for multiple simulations; this function modifies all_quantities but has no return value
When using a differential equation solver to determine the time evolution of a dynamical system's state, it is typically necessary to treat the values of the differential quantities as a vector where they take a particular order, in contrast to our usual method of storing quantities in state_map objects where their values are accessed via their names and do not have a defined order. In this situation, the get_differential_quantity_names and get_differential_quantities methods are essential, since they return the names and values of the differential quantities in a defined order. When the calculate_derivative method is called, the values of the differential quantities are expected to be supplied in the same order defined by get_differential_quantity_names, and the derivatives are also returned in that order.
Once a time sequence of differential quantity values has been determined by a solver, it is typically necessary to retrieve the values of all state quantities that change during a simulation. This can be achieved using additional public methods. First, the names of all such quantities can be determined using the get_output_quantity_names method. Then, pointers to the values of these quantities in the central map can be obtained using the get_quantity_access_ptrs method. Finally, for each value of time and the differential quantities, the update_all_quantities method can be called to update all_quantities, and the access pointers can be used to retrieve the updated values from all_quantities. Rather than explicitly calling these methods, this procedure can be performed using the get_results_from_system free function.
Definition at line 139 of file dynamical_system.h.
Constructor & Destructor Documentation
dynamical_system()
dynamical_system (state_map const & init_values, state_map const & params, state_vector_map const & drivers, string_vector const & dir_module_names, string_vector const & differential_module_names)
Definition at line 5 of file dynamical_system.cpp.
References all_quantities, at(), define_quantity_map(), differential_module_names, differential_modules, differential_quantity_derivatives, differential_quantity_ptr_pairs, direct_module_names, direct_modules, driver_quantity_ptr_pairs, drivers, find_unique_module_outputs(), get_evaluation_order(), get_module_vector(), get_pointer_pairs(), keys(), startup_message, string_set_to_string_vector(), timestep_ptr, and validate_dynamical_system_inputs().
Member Function Documentation
calculate_derivative()
void calculate_derivative (const vector_type & x, vector_type & dxdt, const time_type & t)
Calculates derivatives for each of the differential quantities based on supplied values for the differential quantities and the time. The function signature is set by the boost::odeint library.
Parameters
[in] x values of the differential quantities
[out] dxdt derivatives of the differential quantities calculated using x and t
[in] t the time
Definition at line 281 of file dynamical_system.h.
References ncalls, run_differential_modules(), and update_all_quantities().
Referenced by R_system_derivatives().
generate_startup_report()
string generate_startup_report () const inline
Definition at line 182 of file dynamical_system.h.
References startup_message.
generate_usage_report()
string generate_usage_report () const inline
Definition at line 184 of file dynamical_system.h.
References ncalls.
get_differential_quantities()
void get_differential_quantities (vector_type & x) const
Updates a vector with the current values of all the differential quantities.
Parameters
[out] x An object capable of containing the values of the differential quantities, typically either a std::vector<double> or a boost::numeric::ublas::vector<double>
Definition at line 239 of file dynamical_system.h.
References differential_quantity_ptr_pairs.
Referenced by R_system_derivatives().
get_differential_quantity_names()
string_vector get_differential_quantity_names () const inline
Definition at line 176 of file dynamical_system.h.
References initial_values, and keys().
Referenced by R_system_derivatives().
get_ncalls()
int get_ncalls () const inline
Definition at line 180 of file dynamical_system.h.
References ncalls.
get_ntimes()
size_t get_ntimes () const inline
Definition at line 150 of file dynamical_system.h.
References drivers.
get_output_quantity_names()
string_vector get_output_quantity_names () const
Returns a vector of the names of all quantities that may change throughout a simulation.
The quantities that change are:
quantities whose derivatives are calculated by differential modules, i.e., the differential quantities
quantities whose instantaneous values are calculated by direct modules, i.e., the direct quantities
the drivers
Note
Even though each variable in the initial values should correspond to a derivative calculated by some differential module, it is possible and permissible to have some quantity \(v\) in the initial values that doesn't correspond to any such derivative. In this case, a differential equation \(dv/dt = 0\) is assumed. So such variables in fact do not change during the course of the simulation.
Definition at line 170 of file dynamical_system.cpp.
References at(), direct_module_names, drivers, get_defined_quantity_names(), and initial_values.
get_quantity_access_ptrs()
vector< const double * > get_quantity_access_ptrs (string_vector quantity_names) const
Returns pointers that can be used to access quantity values from the dynamical_system's central map of quantities.
Definition at line 140 of file dynamical_system.cpp.
References all_quantities.
requires_euler_ode_solver()
bool requires_euler_ode_solver () const inline
Check whether the dynamical_system requires a fixed step Euler ODE solver based on the modules that it uses.
Definition at line 158 of file dynamical_system.h.
References check_euler_requirement(), differential_modules, and direct_modules.
reset()
void reset ()
Resets all internally stored quantities back to their original values.
Definition at line 107 of file dynamical_system.cpp.
References all_quantities, direct_modules, initial_values, run_module_list(), and update_drivers().
reset_ncalls()
void reset_ncalls () inline
Definition at line 181 of file dynamical_system.h.
References ncalls.
run_differential_modules()
void run_differential_modules (vector_type & dxdt) private
Calculates a derivative from the internally stored quantity map by running all the differential modules.
Parameters
[out] dxdt a vector for storing the derivative (passed by reference for speed)
Definition at line 322 of file dynamical_system.h.
References differential_modules, differential_quantity_derivatives, differential_quantity_ptr_pairs, run_module_list(), and timestep_ptr.
Referenced by calculate_derivative().
update_all_quantities()
void update_all_quantities (const vector_type & x, const time_type & t)
Updates all quantities in the internally stored map (including ones calculated by direct modules) based on supplied values for the differential quantities and the time.
Parameters
[in] x an object containing new values for the differential quantities, typically either a std::vector<double> or a boost::numeric::ublas::vector<double>
[in] t the time
Definition at line 259 of file dynamical_system.h.
References direct_modules, run_module_list(), update_differential_quantities(), and update_drivers().
Referenced by calculate_derivative().
update_differential_quantities()
void update_differential_quantities (vector_type const & new_values) private
Updates the system's internally stored values for the differential quantities to the ones in new_values.
Definition at line 307 of file dynamical_system.h.
References differential_quantity_ptr_pairs.
Referenced by update_all_quantities().
update_drivers() [1/2]
void update_drivers (double time_indx) private
Updates values of the drivers in the internally stored quantity map to match their values in the internally stored drivers table at time time_index; values of the drivers at non-integer values of time_index are determined using linear interpolation.
Definition at line 120 of file dynamical_system.cpp.
References driver_quantity_ptr_pairs.
Referenced by reset(), and update_all_quantities().
update_drivers() [2/2]
void update_drivers (time_type time_indx) private
Updates values of the drivers in the internally stored quantity map to match their values in the internally stored drivers table at time time_index, which should be a discrete index such as an int or size_t.
Definition at line 295 of file dynamical_system.h.
References driver_quantity_ptr_pairs.
Member Data Documentation
all_quantities
state_map all_quantities private
Definition at line 201 of file dynamical_system.h.
Referenced by dynamical_system(), get_quantity_access_ptrs(), and reset().
differential_module_names
const string_vector differential_module_names private
Definition at line 198 of file dynamical_system.h.
Referenced by dynamical_system().
differential_modules
module_vector differential_modules private
Definition at line 206 of file dynamical_system.h.
Referenced by dynamical_system(), requires_euler_ode_solver(), and run_differential_modules().
differential_quantity_derivatives
state_map differential_quantity_derivatives private
Definition at line 202 of file dynamical_system.h.
Referenced by dynamical_system(), and run_differential_modules().
differential_quantity_ptr_pairs
vector<pair<double*, const double*> > differential_quantity_ptr_pairs private
Definition at line 210 of file dynamical_system.h.
Referenced by dynamical_system(), get_differential_quantities(), run_differential_modules(), and update_differential_quantities().
direct_module_names
string_vector direct_module_names private
Definition at line 197 of file dynamical_system.h.
Referenced by dynamical_system(), and get_output_quantity_names().
direct_modules
module_vector direct_modules private
Definition at line 205 of file dynamical_system.h.
Referenced by dynamical_system(), requires_euler_ode_solver(), reset(), and update_all_quantities().
driver_quantity_ptr_pairs
vector<pair<double*, const vector<double>*> > driver_quantity_ptr_pairs private
Definition at line 211 of file dynamical_system.h.
Referenced by dynamical_system(), and update_drivers().
drivers
const state_vector_map drivers private
Definition at line 196 of file dynamical_system.h.
Referenced by dynamical_system(), get_ntimes(), and get_output_quantity_names().
initial_values
const state_map initial_values private
Definition at line 194 of file dynamical_system.h.
Referenced by get_differential_quantity_names(), get_output_quantity_names(), and reset().
ncalls
int ncalls = 0 private
Definition at line 226 of file dynamical_system.h.
Referenced by calculate_derivative(), generate_usage_report(), get_ncalls(), and reset_ncalls().
parameters
const state_map parameters private
Definition at line 195 of file dynamical_system.h.
startup_message
string startup_message private
Definition at line 227 of file dynamical_system.h.
Referenced by dynamical_system(), and generate_startup_report().
timestep_ptr
double* timestep_ptr private
Definition at line 209 of file dynamical_system.h.
Referenced by dynamical_system(), and run_differential_modules().
The documentation for this class was generated from the following files:
/github/workspace/src/dynamical_system.h
/github/workspace/src/dynamical_system.cpp