The BioCro C++ Library: /github/workspace/src/modules.cpp File Reference
modules.cpp File Reference
#include "modules.h"
Functions
void run_module_list (module_vector const &modules)
Runs each module in the input list.
Function Documentation
run_module_list()
void run_module_list (module_vector const & modules)
Runs each module in the input list.
Parameters
[in] modules A vector of unique pointers to module objects
Definition at line 8 of file modules.cpp.
Referenced by dynamical_system::reset(), dynamical_system::run_differential_modules(), and dynamical_system::update_all_quantities().