The BioCro C++ Library: /github/workspace/src/R_system_derivatives.cpp File Reference
R_system_derivatives.cpp File Reference
#include <Rinternals.h>
#include <vector>
#include <string>
#include <exception>
#include "state_map.h"
#include "dynamical_system.h"
#include "R_helper_functions.h"
Functions
SEXP R_system_derivatives (SEXP differential_quantities, SEXP time, SEXP parameters, SEXP drivers, SEXP direct_module_names, SEXP differential_module_names)
Creates a dynamical_system object from the differential quantities, parameters, drivers, and modules, and then uses the system object to determine the derivatives of the differential quantities at the specified time.
Function Documentation
R_system_derivatives()
SEXP R_system_derivatives (SEXP differential_quantities, SEXP time, SEXP parameters, SEXP drivers, SEXP direct_module_names, SEXP differential_module_names)
Creates a dynamical_system object from the differential quantities, parameters, drivers, and modules, and then uses the system object to determine the derivatives of the differential quantities at the specified time.
Parameters
[in] differential_quantities An R list of named elements representing the current values of the differential quantities
[in] time An R numeric vector with one element specifying the time index
[in] parameters An R list of named elements representing the parameters
[in] drivers An R data frame representing the time series of the drivers
[in] direct_module_names An R string vector of the names of the direct modules
[in] differential_module_names An R string vector of the names of the differential modules
Returns
An R list of named elements representing the derivatives of the differential quantities
Definition at line 41 of file R_system_derivatives.cpp.
References dynamical_system::calculate_derivative(), dynamical_system::get_differential_quantities(), dynamical_system::get_differential_quantity_names(), list_from_map(), make_vector(), map_from_list(), map_vector_from_list(), and parameters.