The BioCro C++ Library: module_wrapper_base Class Reference
module_wrapper_base Class Reference abstract
#include <module_wrapper.h>
Public Member Functions
virtual string_vector get_inputs ()=0
virtual string_vector get_outputs ()=0
virtual std::string get_name ()=0
virtual std::unique_ptr< module_base > createModule (state_map const &input_quantities, state_map *output_quantities)=0
virtual ~module_wrapper_base ()=0
Detailed Description
Definition at line 17 of file module_wrapper.h.
Constructor & Destructor Documentation
~module_wrapper_base()
~module_wrapper_base () inline pure virtual
Definition at line 32 of file module_wrapper.h.
Member Function Documentation
createModule()
virtual std::unique_ptr<module_base> createModule (state_map const & input_quantities, state_map * output_quantities) pure virtual
Implemented in module_wrapper< T >.
Referenced by R_evaluate_module(), and R_module_info().
get_inputs()
virtual string_vector get_inputs () pure virtual
Implemented in module_wrapper< T >.
Referenced by R_module_info().
get_name()
virtual std::string get_name () pure virtual
Implemented in module_wrapper< T >.
Referenced by R_module_info().
get_outputs()
virtual string_vector get_outputs () pure virtual
Implemented in module_wrapper< T >.
Referenced by R_evaluate_module(), and R_module_info().
The documentation for this class was generated from the following file:
/github/workspace/src/module_wrapper.h