The BioCro C++ Library: boost_ode_solver< state_type > Class Template Reference
boost_ode_solver< state_type > Class Template Reference abstract
A class representing a generic boost system ode_solver.
#include <boost_ode_solvers.h>
Public Member Functions
boost_ode_solver (std::string ode_solver_name, bool check_euler_requirement, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps)
Public Member Functions inherited from ode_solver
ode_solver (std::string ode_solver_name, bool should_check_euler_requirement, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps)
virtual ~ode_solver ()
state_vector_map integrate (std::shared_ptr< dynamical_system > sys)
std::string generate_info_report () const
std::string generate_integrate_report () const
Protected Member Functions
template<class stepper_type >
void run_integrate_const (stepper_type stepper, dynamical_system_caller syscall, push_back_state_and_time< state_type > observer)
Protected Member Functions inherited from ode_solver
double get_output_step_size () const
double get_adaptive_rel_error_tol () const
double get_adaptive_abs_error_tol () const
int get_adaptive_max_steps () const
Private Member Functions
state_vector_map do_integrate (std::shared_ptr< dynamical_system > sys) override
virtual void do_boost_integrate (dynamical_system_caller syscall, push_back_state_and_time< state_type > &observer)=0
std::string get_param_info () const override
virtual std::string get_boost_param_info () const =0
std::string get_solution_info () const override
Private Attributes
std::string boost_error_string
size_t nsteps
state_type state
std::vector< state_type > state_vec
std::vector< double > time_vec
std::string observer_message
Detailed Description
template<class state_type>
class boost_ode_solver< state_type >
A class representing a generic boost system ode_solver.
Definition at line 13 of file boost_ode_solvers.h.
Constructor & Destructor Documentation
boost_ode_solver()
boost_ode_solver (std::string ode_solver_name, bool check_euler_requirement, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps) inline
Definition at line 16 of file boost_ode_solvers.h.
Member Function Documentation
do_boost_integrate()
virtual void do_boost_integrate (dynamical_system_caller syscall, push_back_state_and_time< state_type > & observer) private pure virtual
Implemented in boost_rkck54_ode_solver< state_type >, boost_rk4_ode_solver< state_type >, and boost_euler_ode_solver< state_type >.
do_integrate()
state_vector_map do_integrate (std::shared_ptr< dynamical_system > sys) override private virtual
Implements ode_solver.
Definition at line 75 of file boost_ode_solvers.h.
References get_results_from_system().
get_boost_param_info()
virtual std::string get_boost_param_info () const private pure virtual
Implemented in boost_rsnbrk_ode_solver, boost_rkck54_ode_solver< state_type >, boost_rk4_ode_solver< state_type >, and boost_euler_ode_solver< state_type >.
Referenced by boost_ode_solver< state_type >::get_param_info().
get_param_info()
std::string get_param_info () const inline override private virtual
Implements ode_solver.
Definition at line 48 of file boost_ode_solvers.h.
References boost_ode_solver< state_type >::get_boost_param_info(), and ode_solver::get_output_step_size().
get_solution_info()
std::string get_solution_info () const inline override private virtual
Implements ode_solver.
Definition at line 58 of file boost_ode_solvers.h.
References boost_ode_solver< state_type >::boost_error_string, boost_ode_solver< state_type >::nsteps, and boost_ode_solver< state_type >::observer_message.
run_integrate_const()
void run_integrate_const (stepper_type stepper, dynamical_system_caller syscall, push_back_state_and_time< state_type > observer) protected
Definition at line 99 of file boost_ode_solvers.h.
References dynamical_system_pointer_wrapper::get_ntimes().
Referenced by boost_euler_ode_solver< state_type >::do_boost_integrate(), boost_rk4_ode_solver< state_type >::do_boost_integrate(), and boost_rkck54_ode_solver< state_type >::do_boost_integrate().
Member Data Documentation
boost_error_string
std::string boost_error_string private
Definition at line 38 of file boost_ode_solvers.h.
Referenced by boost_ode_solver< state_type >::get_solution_info().
nsteps
size_t nsteps private
Definition at line 39 of file boost_ode_solvers.h.
Referenced by boost_ode_solver< state_type >::get_solution_info().
observer_message
std::string observer_message private
Definition at line 44 of file boost_ode_solvers.h.
Referenced by boost_ode_solver< state_type >::get_solution_info().
state
state_type state private
Definition at line 41 of file boost_ode_solvers.h.
state_vec
std::vector<state_type> state_vec private
Definition at line 42 of file boost_ode_solvers.h.
time_vec
std::vector<double> time_vec private
Definition at line 43 of file boost_ode_solvers.h.
The documentation for this class was generated from the following file:
/github/workspace/src/ode_solver_library/boost_ode_solvers.h