The BioCro C++ Library: /github/workspace/src/module_library/c3CanAC.cpp File Reference
c3CanAC.cpp File Reference
#include "BioCro.h"
#include "c3photo.hpp"
#include "../constants.h"
Functions
struct Can_Str c3CanAC (double LAI, double cosine_zenith_angle, double solarR, double air_temperature, double RH, double WindSpeed, int nlayers, double Vmax, double Jmax, double tpu_rate_max, double Rd, double Catm, double o2, double b0, double b1, double Gs_min, double theta, double kd, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double chil, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, double growth_respiration_fraction, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance, double minimum_gbw, double WindSpeedHeight)
Function Documentation
c3CanAC()
struct Can_Str c3CanAC (double LAI, double cosine_zenith_angle, double solarR, double air_temperature, double RH, double WindSpeed, int nlayers, double Vmax, double Jmax, double tpu_rate_max, double Rd, double Catm, double o2, double b0, double b1, double Gs_min, double theta, double kd, double heightf, double leafN, double kpLN, double lnb0, double lnb1, int lnfun, double chil, double StomataWS, double specific_heat_of_air, double atmospheric_pressure, double growth_respiration_fraction, int water_stress_approach, double electrons_per_carboxylation, double electrons_per_oxygenation, double absorptivity_par, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance, double minimum_gbw, double WindSpeedHeight)
Definition at line 1 of file c3CanAC.cpp.
References Can_Str::Assim, c3_str::Assim, Light_profile::average_absorbed_shortwave, c3EvapoTrans(), c3photoC(), Can_Str::canopy_conductance, Can_Str::canopy_transpiration_penman, Can_Str::canopy_transpiration_priestly, ET_Str::Deltat, Light_model::diffuse_irradiance_fraction, Light_model::direct_irradiance_fraction, ET_Str::EPenman, ET_Str::EPriestly, Can_Str::GrossAssim, c3_str::GrossAssim, c3_str::Gs, Light_profile::height, lightME(), LNprof(), RHprof(), Light_profile::shaded_fraction, Light_profile::shaded_incident_ppfd, Light_profile::sunlit_fraction, Light_profile::sunlit_incident_ppfd, sunML(), Can_Str::Trans, ET_Str::TransR, and WINDprof().