The BioCro C++ Library: /github/workspace/src/validate_dynamical_system.h File Reference
validate_dynamical_system.h File Reference
#include <string>
#include <set>
#include <functional>
#include "state_map.h"
#include "modules.h"
#include "module_library/module_wrapper_factory.h"
Functions
bool validate_dynamical_system_inputs (std::string &message, state_map initial_values, state_map params, state_vector_map drivers, string_vector direct_module_names, string_vector differential_module_names)
Checks over a group of quantities and modules to ensure they can be used to create a valid system.
std::string analyze_system_inputs (state_map initial_values, state_map params, state_vector_map drivers, string_vector direct_module_names, string_vector differential_module_names)
Provides information about a set of system inputs that is not strictly required to check validity.
state_map define_quantity_map (std::vector< state_map > state_maps, std::vector< string_vector > module_name_vectors)
Assembles a "master" state_map from a group of state_maps and a list of modules.
string_vector find_duplicate_quantity_definitions (string_vector quantity_names)
Finds quantities that are defined multiple times in a vector of strings.
string_vector find_undefined_module_inputs (string_vector quantity_names, std::vector< string_vector > module_name_vectors)
Finds quantities that are required by modules but are not defined by quantity_names. The output includes the module associated with each undefined input.
string_vector find_undefined_module_outputs (string_vector quantity_names, std::vector< string_vector > module_name_vectors)
Finds quantities that are output by modules but are not defined by quantity_names. The output includes the module associated with each undefined output.
string_set find_unique_module_inputs (std::vector< string_vector > module_name_vectors)
Returns a set containing all unique inputs to the modules.
string_set find_unique_module_outputs (std::vector< string_vector > module_name_vectors)
Returns a set containing all unique outputs produced by the modules.
string_set find_strictly_required_inputs (std::vector< string_vector > module_name_vectors)
Returns a vector containing all inputs to the set of modules that are not outputs produced by previous modules. Note that the order of modules is important here.
string_vector find_unused_input_parameters (std::vector< state_map > state_maps, std::vector< string_vector > module_name_vectors)
Returns parameters in the state maps that are not used as inputs to the modules.
string_vector find_static_output_parameters (std::vector< state_map > state_maps, std::vector< string_vector > module_name_vectors)
Returns parameters in the state maps that are not provided as outputs from the modules.
string_vector find_euler_requirements (string_vector module_names)
Returns modules that require a fixed step size Euler ode_solver.
string_vector find_mischaracterized_modules (string_vector module_names, bool is_differential)
Returns mischaracterized modules, i.e., direct modules in the differential module list or vice-versa.
module_vector get_module_vector (string_vector module_names, state_map const &input_quantities, state_map *output_quantities)
Returns a vector of unique_ptrs to module objects.
std::string add_indented_line (std::string message, std::string text_to_add, int num_spaces)
Adds an indented line to a message.
void insert_quantity_name_if_new (std::string quantity_name, string_vector &target_vector, string_vector &duplicate_vector)
Inserts quantity_name into target_vector if it is not already there. In the case of a duplicate, quantity_name is inserted into duplicates.
void insert_module_param_if_undefined (std::string param_name, std::string module_name, string_vector defined_quantity_names, string_vector &undefined_module_names)
If param_name is not included in defined_quantity_names, a new entry is inserted into undefined_module_names that includes param_name and its associated module_name.
string_vector string_set_to_string_vector (string_set ss)
Converts a string_set to a string_vector.
string_set string_vector_to_string_set (string_vector sv)
Creates a string_set from all the elements of a string_vector.
string_vector string_vector_difference (string_vector find_elements_of_this_vector, string_vector that_are_not_in_this_one)
template<typename string_list_type >
size_t process_criterion (std::string &message, std::function< string_list_type()> criterion_test, std::function< std::string(string_list_type)> form_message)
Template function for testing a system input criterion.
template<typename string_list_type >
std::string create_message (std::string message_if_empty, std::string message_at_beginning, std::string message_at_end, string_list_type string_list, std::string success_indicator="", std::string failure_indicator="")
Forms a user feedback message from a list of quantities, modules, etc.
template<typename string_list_type >
std::string create_marked_message (std::string message_if_empty, std::string message_at_beginning, std::string message_at_end, string_list_type string_list)
Forms a user feedback message from a list of quantities, modules, etc. This function should be used in preference to create_message for the case where a non-empty string_list corresponds to some failure condition and an empty string_list corresponds to success, and we want to prepend success/failure indicators to the message.
template<typename map_type >
void insert_key_names (string_vector &name_vector, const map_type map)
Inserts all the keys from map into name_vector.
template<typename map_with_string_keys >
string_vector get_defined_quantity_names (std::vector< map_with_string_keys > state_maps, std::vector< string_vector > module_name_vectors)
Assembles the names of all quantities defined by a group of state_maps and module outputs, including any duplicates.
template<typename list_type >
void insert_quantity_if_undefined (std::string quantity_name, list_type defined_quantity_names, string_vector &undefined_quantity_names)
If quantity_name is not included in defined_quantity_names, it is inserted into undefined_quantity_names.
template<typename list_type >
bool all_are_in_list (list_type find_these, list_type in_this)
Checks whether all of the elements of list find_these are in the list in_this.
Variables
const std::string success_mark {"[pass] "}
const std::string failure_mark {"[fail] "}
Function Documentation
add_indented_line()
std::string add_indented_line (std::string message, std::string text_to_add, int num_spaces)
Adds an indented line to a message.
Parameters
[in] message The message being added to.
[in] text_to_add The text being appended to message.
[in] num_spaces The number of spaces of indentation for the appended text.
Returns
A string consisting of the input message followed num_spaces space characters followed by text_to_add.
Definition at line 604 of file validate_dynamical_system.cpp.
Referenced by create_message().
all_are_in_list()
bool all_are_in_list (list_type find_these, list_type in_this)
Checks whether all of the elements of list find_these are in the list in_this.
Definition at line 296 of file validate_dynamical_system.h.
analyze_system_inputs()
std::string analyze_system_inputs (state_map initial_values, state_map params, state_vector_map drivers, string_vector direct_module_names, string_vector differential_module_names)
Provides information about a set of system inputs that is not strictly required to check validity.
The following information is reported:
A list of all quantities required by the modules as inputs
A list of unused quantities in the invariant parameter list
A list of unused quantities in the drivers list
A list of quantities in the initial values that lack derivatives
A list of quantities whose derivatives have terms calculated by multiple modules
Definition at line 135 of file validate_dynamical_system.cpp.
References at(), create_message(), find_duplicate_quantity_definitions(), find_euler_requirements(), find_mischaracterized_modules(), find_static_output_parameters(), find_unique_module_inputs(), find_unused_input_parameters(), get_defined_quantity_names(), get_evaluation_order(), has_cyclic_dependency(), and order_ok().
Referenced by R_validate_dynamical_system_inputs().
create_marked_message()
std::string create_marked_message (std::string message_if_empty, std::string message_at_beginning, std::string message_at_end, string_list_type string_list)
Forms a user feedback message from a list of quantities, modules, etc. This function should be used in preference to create_message for the case where a non-empty string_list corresponds to some failure condition and an empty string_list corresponds to success, and we want to prepend success/failure indicators to the message.
Parameters
[in] message_if_empty This is the string that will be returned (surrounded by new-line characters and an initial "success" indicator) if string_list is empty.
[in] message_at_beginning This string is prepended (after being surrounded by new-line characters and an initial "failure" indicator) to the body of the message if string_list is not empty.
[in] message_at_end This string is appended to the body of the message (along with a new-line character) if string_list is not empty.
[in] string_list A list of strings that will form the body of the message.
Definition at line 205 of file validate_dynamical_system.h.
References create_message(), failure_mark, and success_mark.
Referenced by validate_dynamical_system_inputs().
create_message()
std::string create_message (std::string message_if_empty, std::string message_at_beginning, std::string message_at_end, string_list_type string_list, std::string success_indicator = "", std::string failure_indicator = "")
Forms a user feedback message from a list of quantities, modules, etc.
Parameters
[in] message_if_empty This is the string that will be returned (surrounded by new-line characters) if string_list is empty.
[in] message_at_beginning This string is prepended (after being surrounded by new-line characters) to the body of the message if string_list is not empty.
[in] message_at_end This string is appended to the body of the message (along with a new-line character) if string_list is not empty.
[in] string_list A list of strings that will form the body of the message.
Definition at line 153 of file validate_dynamical_system.h.
References add_indented_line().
Referenced by analyze_system_inputs(), and create_marked_message().
define_quantity_map()
state_map define_quantity_map (std::vector< state_map > state_maps, std::vector< string_vector > module_name_vectors)
Assembles a "master" state_map from a group of state_maps and a list of modules.
The resulting state_map will essentially be the union of all the maps in parameter state_maps and an additional map formed by taking as keys all of the output variables from modules in module_name_vectors and setting the corresponding values to zero. The set of keys in the maps in state_maps should not overlap with one another and should be distinct from the module output variable names.
Parameters
state_maps A list (presented as a std::vector) of state_maps.
module_name_vectors A list of lists (present as a std::vector of strint_vectors) of module names.
Returns
a state_map which is the union of all maps in state_maps together a map whose keys are all the output parameters of modules in module_name_vectors and whose values are all zero.
Definition at line 289 of file validate_dynamical_system.cpp.
Referenced by dynamical_system::dynamical_system().
find_duplicate_quantity_definitions()
string_vector find_duplicate_quantity_definitions (string_vector quantity_names)
Finds quantities that are defined multiple times in a vector of strings.
Parameters
quantity_names A list (presented as a vector of strings) of names of quantities. Generally these will be names of state variables, environment variables ("varying parameters"), system constants ("invariant parameters"), or derived quantites (outputs of direct modules).
Returns
A alphabetized list (presented as a vector of strings) of all quantities appearing more than once in the input list.
Definition at line 328 of file validate_dynamical_system.cpp.
References insert_quantity_name_if_new().
Referenced by analyze_system_inputs(), and validate_dynamical_system_inputs().
find_euler_requirements()
string_vector find_euler_requirements (string_vector module_names)
Returns modules that require a fixed step size Euler ode_solver.
Definition at line 511 of file validate_dynamical_system.cpp.
References find_unique_module_inputs(), find_unique_module_outputs(), and get_module_vector().
Referenced by analyze_system_inputs().
find_mischaracterized_modules()
string_vector find_mischaracterized_modules (string_vector module_names, bool is_differential)
Returns mischaracterized modules, i.e., direct modules in the differential module list or vice-versa.
Definition at line 544 of file validate_dynamical_system.cpp.
References find_unique_module_inputs(), find_unique_module_outputs(), and get_module_vector().
Referenced by analyze_system_inputs().
find_static_output_parameters()
string_vector find_static_output_parameters (std::vector< state_map > state_maps, std::vector< string_vector > module_name_vectors)
Returns parameters in the state maps that are not provided as outputs from the modules.
Definition at line 488 of file validate_dynamical_system.cpp.
References find_unique_module_outputs(), insert_quantity_if_undefined(), keys(), and parameters.
Referenced by analyze_system_inputs().
find_strictly_required_inputs()
string_set find_strictly_required_inputs (std::vector< string_vector > module_name_vectors)
Returns a vector containing all inputs to the set of modules that are not outputs produced by previous modules. Note that the order of modules is important here.
Definition at line 431 of file validate_dynamical_system.cpp.
References insert_quantity_if_undefined(), and string_vector_to_string_set().
find_undefined_module_inputs()
string_vector find_undefined_module_inputs (string_vector quantity_names, std::vector< string_vector > module_name_vectors)
Finds quantities that are required by modules but are not defined by quantity_names. The output includes the module associated with each undefined input.
Definition at line 347 of file validate_dynamical_system.cpp.
References insert_module_param_if_undefined().
Referenced by validate_dynamical_system_inputs().
find_undefined_module_outputs()
string_vector find_undefined_module_outputs (string_vector quantity_names, std::vector< string_vector > module_name_vectors)
Finds quantities that are output by modules but are not defined by quantity_names. The output includes the module associated with each undefined output.
Definition at line 371 of file validate_dynamical_system.cpp.
References insert_module_param_if_undefined().
Referenced by validate_dynamical_system_inputs().
find_unique_module_inputs()
string_set find_unique_module_inputs (std::vector< string_vector > module_name_vectors)
Returns a set containing all unique inputs to the modules.
Definition at line 393 of file validate_dynamical_system.cpp.
Referenced by analyze_system_inputs(), find_euler_requirements(), find_mischaracterized_modules(), and find_unused_input_parameters().
find_unique_module_outputs()
string_set find_unique_module_outputs (std::vector< string_vector > module_name_vectors)
Returns a set containing all unique outputs produced by the modules.
Definition at line 412 of file validate_dynamical_system.cpp.
Referenced by dynamical_system::dynamical_system(), find_euler_requirements(), find_mischaracterized_modules(), and find_static_output_parameters().
find_unused_input_parameters()
string_vector find_unused_input_parameters (std::vector< state_map > state_maps, std::vector< string_vector > module_name_vectors)
Returns parameters in the state maps that are not used as inputs to the modules.
Definition at line 454 of file validate_dynamical_system.cpp.
References find_unique_module_inputs(), insert_quantity_if_undefined(), keys(), and parameters.
Referenced by analyze_system_inputs().
get_defined_quantity_names()
string_vector get_defined_quantity_names (std::vector< map_with_string_keys > state_maps, std::vector< string_vector > module_name_vectors)
Assembles the names of all quantities defined by a group of state_maps and module outputs, including any duplicates.
Parameters
[in] state_maps A collection of sets of named quantities presented as a vector of map_with_string_keys objects. Generally, this will either be empty or will consist of the initial values of the system, the set of parameters, and the initial values of the drivers.
[in] module_name_vectors A collection of sets of module names presented as a vector of vectors. Usually, this collection will either be empty or will contain only a single item—a set of direct module names or a set of differential module names.
Returns
A vector consisting of the names of all quantities defined in either of the function arguments. If a quantity is defined more than once, it will appear in the output vector more than once. A quantity is considered to be "defined" by the state_maps argument value if it is a key in one of the given maps. It is considered "defined" by the module_name_vectors argument value if it is a name of an output variable of some module named in any set in the collection.
Definition at line 253 of file validate_dynamical_system.h.
References insert_key_names().
Referenced by analyze_system_inputs(), dynamical_system::get_output_quantity_names(), and validate_dynamical_system_inputs().
get_module_vector()
module_vector get_module_vector (string_vector module_names, state_map const & input_quantities, state_map * output_quantities)
Returns a vector of unique_ptrs to module objects.
Definition at line 576 of file validate_dynamical_system.cpp.
Referenced by dynamical_system::dynamical_system(), find_euler_requirements(), and find_mischaracterized_modules().
insert_key_names()
void insert_key_names (string_vector & name_vector, const map_type map)
Inserts all the keys from map into name_vector.
Definition at line 222 of file validate_dynamical_system.h.
References keys().
Referenced by get_defined_quantity_names().
insert_module_param_if_undefined()
void insert_module_param_if_undefined (std::string param_name, std::string module_name, string_vector defined_quantity_names, string_vector & undefined_module_names)
If param_name is not included in defined_quantity_names, a new entry is inserted into undefined_module_names that includes param_name and its associated module_name.
Definition at line 645 of file validate_dynamical_system.cpp.
Referenced by find_undefined_module_inputs(), and find_undefined_module_outputs().
insert_quantity_if_undefined()
void insert_quantity_if_undefined (std::string quantity_name, list_type defined_quantity_names, string_vector & undefined_quantity_names)
If quantity_name is not included in defined_quantity_names, it is inserted into undefined_quantity_names.
Definition at line 281 of file validate_dynamical_system.h.
Referenced by find_static_output_parameters(), find_strictly_required_inputs(), find_unused_input_parameters(), and string_vector_difference().
insert_quantity_name_if_new()
void insert_quantity_name_if_new (std::string quantity_name, string_vector & target_vector, string_vector & duplicates)
Inserts quantity_name into target_vector if it is not already there. In the case of a duplicate, quantity_name is inserted into duplicates.
Parameters
[in] quantity_name A string (the name of a quantity).
[in/out] target_vector A vector of strings. If quantity_name wasn't in the list to begin with, it will be appended.
[in/out] duplicates A vector of strings. If quantity_name was already in target_vector, it will be appended to duplicates.
Definition at line 628 of file validate_dynamical_system.cpp.
Referenced by find_duplicate_quantity_definitions().
process_criterion()
size_t process_criterion (std::string & message, std::function< string_list_type()> criterion_test, std::function< std::string(string_list_type)> form_message)
Template function for testing a system input criterion.
This function first calls criterion_test, which should return some kind of container of strings, e.g. std::vector<std::string> or std::set<std::string>. A non-empty result generally corresponds to failure to meet the criterion.
The output of criterion_test is then passed to form_message, which should create a user feedback message based on the result of the criterion test.
The output of form_message is added to the message input (passed by reference).
Finally, the number of elements in the output of criterion_test is returned. Again, a non-zero value generally corresponds to a failure to meet the criterion specified by criterion_test.
Parameters
[in,out] message A string, to which this function will append the result of the criterion test.
[in] criterion_test A function object having no input parameters and returning a string_list_type container.
[in] form_message A function object having on parameter of type string_list_type and returning a string. This will generally be a function that cobbles together a readable message from the collection of strings given as input.
Returns
The number of elements in the container returned by criterion_test. Generally, a non-zero value corresponds to a failure to meet the criterion tested by criterion_test.
Definition at line 121 of file validate_dynamical_system.h.
string_set_to_string_vector()
string_vector string_set_to_string_vector (string_set ss)
Converts a string_set to a string_vector.
Definition at line 659 of file validate_dynamical_system.cpp.
Referenced by dynamical_system::dynamical_system().
string_vector_difference()
string_vector string_vector_difference (string_vector find_elements_of_this_vector, string_vector that_are_not_in_this_one)
Definition at line 681 of file validate_dynamical_system.cpp.
References insert_quantity_if_undefined().
string_vector_to_string_set()
string_set string_vector_to_string_set (string_vector sv)
Creates a string_set from all the elements of a string_vector.
Definition at line 672 of file validate_dynamical_system.cpp.
Referenced by find_strictly_required_inputs().
validate_dynamical_system_inputs()
bool validate_dynamical_system_inputs (std::string & message, state_map initial_values, state_map params, state_vector_map drivers, string_vector direct_module_names, string_vector differential_module_names)
Checks over a group of quantities and modules to ensure they can be used to create a valid system.
Parameters
[in,out] message Validation feedback is added to this string.
Returns
true if the inputs are valid, false otherwise.
The following criteria are used to determine validity:
Each quantity is specified only once.
All module inputs are specified.
Derivatives are calculated only for quantities in the initial values.
Direct modules can be ordered in such a way that inputs are calculated before they are accessed.
We consider a quantity to have been "specified" (or "defined") if it is a key in one of the maps initial_values, params, or drivers, or, if it is an output variable of one of the direct modules listed in direct_module_names.
Criterion 2 and criterion 4 are related: Criterion 2 requires merely that each input to a direct or differential module is either a variable in the initial values, is one of the parameters, or is an output of some direct module. Criterion 4 goes further for the case of a direct module where an input quantity is provided by the output of some other direct module: It requires that the direct modules can be ordered in such a way that each of a module's input quantities that is neither a parameter or a quantity in the initial values be provided by the output of a module earlier in the list.
Notably absent from these criteria is a requirement that a derivative be calculated for every value given in the initial values. Values in the initial values that are not outputs of any differential module are assumed to have a derivative of zero, that is, they are assumed to be constant.
Definition at line 44 of file validate_dynamical_system.cpp.
References at(), create_marked_message(), find_duplicate_quantity_definitions(), find_undefined_module_inputs(), find_undefined_module_outputs(), get_defined_quantity_names(), has_cyclic_dependency(), and keys().
Referenced by dynamical_system::dynamical_system(), and R_validate_dynamical_system_inputs().
Variable Documentation
failure_mark
const std::string failure_mark {"[fail] "}
Definition at line 12 of file validate_dynamical_system.h.
Referenced by create_marked_message().
success_mark
const std::string success_mark {"[pass] "}
Definition at line 11 of file validate_dynamical_system.h.
Referenced by create_marked_message().