The BioCro C++ Library: /github/workspace/src/module_library/AuxBioCro.h File Reference
AuxBioCro.h File Reference
#include <map>
#include "../constants.h"
Classes
struct Light_profile
struct ET_Str
struct Can_Str
struct ws_str
struct soilML_str
struct dbp_str
struct soilText_str
struct seqRD_str
struct rd_str
struct frostParms
struct nitroParms
struct crop_phenology
struct crop_phenology::minerals1
Macros
#define MAXLAY 200 /* Maximum number of layers */
Enumerations
enum class SoilType {
sand , loamy_sand , sandy_loam , loam ,
silt_loam , sandy_clay_loam , clay_loam , silty_clay_loam ,
sandy_clay , silty_clay , clay
}
Functions
const soilText_str get_soil_properties (SoilType soiltype)
soilText_str get_soil_properties (int soiltype)
struct seqRD_str seqRootDepth (double to, int lengthOut)
struct rd_str rootDist (int layer, double rootDepth, double *depths, double rfl)
double leaf_boundary_layer_conductance_nikolov (double windspeed, double leafwidth, double air_temperature, double delta_t, double stomcond, double water_vapor_pressure, double minimum_gbw)
Caluclates the conductance for water vapor flow between the leaf surface and the atmosphere (AKA, the boundary layer conductance) using a model described in Nikolov, Massman, and Schoettle (1995).
double leaf_boundary_layer_conductance_thornley (double CanopyHeight, double WindSpeed, double minimum_gbw, double WindSpeedHeight)
Caluclates the conductance for water vapor flow between the leaf surface and the atmosphere (AKA, the boundary layer conductance) using a model described in Thornley and Johnson (1990).
void LNprof (double LeafN, double LAI, int nlayers, double kpLN, double *leafNla)
double arrhenius_exponent (double c, double activation_energy, double temperature)
Calculates the exponential term of the Arrhenius equation.
double saturation_vapor_pressure (double air_temperature)
Determine saturation water vapor pressure (Pa) from air temperature (degrees C) using the Arden Buck equation.
double TempToSFS (double Temp)
Determine the derivative of saturation water vapor pressure with respect to temperature at a particular value of air temperature.
double TempToLHV (double Temp)
Determine the latent heat of vaporization for water from its temperature.
double TempToDdryA (double Temp)
Determines the density of dry air from the air temperature.
Variables
const std::map< SoilType, soilText_str > soil_parameters
Macro Definition Documentation
MAXLAY
#define MAXLAY 200 /* Maximum number of layers */
Definition at line 18 of file AuxBioCro.h.
Enumeration Type Documentation
SoilType
enum SoilType strong
Enumerator
sand
loamy_sand
sandy_loam
loam
silt_loam
sandy_clay_loam
clay_loam
silty_clay_loam
sandy_clay
silty_clay
clay
Definition at line 91 of file AuxBioCro.h.
Function Documentation
arrhenius_exponent()
double arrhenius_exponent (double c, double activation_energy, double temperature) inline
Calculates the exponential term of the Arrhenius equation.
The Arrhenius equation gives the dependence of the rate constant of a chemical reaction on the absolute temperature and is often written as
k = A * e^(-E_a / R / T) (1)
where k is the rate constant, E_a is the activation energy, R is the ideal gas constant, and T is the absolute temperature. As T approaches infinity, E_a / R / T approaches zero and so k approaches A. Thus, A represents the rate constant in the limit of infinite temperature. From a practical standpoint, A is not a particularly useful parameter and for this reason it is often written as
A = k_0 * e^c (2)
where k_0 is the rate constant measured at a reference temperature (e.g. 25 degrees C) and c is a dimensionless parameter chosen so that k = k_0 at the reference temperature.
In order to make this function reusable, it only calculates the exponential factor, which is always dimensionless. I.e., it calculates e^(c - E_a / R / T).
Parameters
[in] c Dimensionless parameter related to the reference temperature at which the rate constant was measured
[in] activation_energy Activation energy of the reaction in J / mol
[in] temperature Absolute temperature in Kelvin
Returns
Return The Arrhenius exponent e^(c - E_a / R / T)
Definition at line 231 of file AuxBioCro.h.
get_soil_properties() [1/2]
soilText_str get_soil_properties (int soiltype)
Definition at line 1493 of file AuxBioCro.cpp.
get_soil_properties() [2/2]
const soilText_str get_soil_properties (SoilType soiltype)
Definition at line 1497 of file AuxBioCro.cpp.
References soil_parameters.
leaf_boundary_layer_conductance_nikolov()
double leaf_boundary_layer_conductance_nikolov (double windspeed, double leafwidth, double air_temperature, double delta_t, double stomcond, double water_vapor_pressure, double minimum_gbw)
Caluclates the conductance for water vapor flow between the leaf surface and the atmosphere (AKA, the boundary layer conductance) using a model described in Nikolov, Massman, and Schoettle (1995).
In this model, two types of gas flow are considered: "forced" flow driven by wind-created eddy currents and "free" flow driven by temperature-related buoyancy effects. The overall conductance is determined to be the larger of the free and forced conductances.
In this function, we use equations 29, 33, 34, and 35 to calculate boundary layer conductance. This is the same approach taken in the MLcan model of Drewry et al. (2010).
In this model, the minimum possible boundary layer conductance that could occur is zero. This would happen if wind speed is zero and the air and leaf temperatures are the same. In realistic field conditions, boundary layer conductance can never truly be zero. To accomodate this, an option is provided for setting a minimum value for the boundary layer counductance.
References:
Nikolov, N. T., Massman, W. J. & Schoettle, A. W. "Coupling biochemical and biophysical processes at the leaf level: an equilibrium photosynthesis model for leaves of C3 plants" Ecological Modelling 80, 205–235 (1995)
Drewry, D. T. et al. "Ecohydrological responses of dense canopies to environmental variability: 1. Interplay between vertical structure and photosynthetic pathway" Journal of Geophysical Research: Biogeosciences 115, (2010)
Parameters
[in] windspeed The wind speed in m / s
[in] leafwidth The characteristic leaf dimension in m
[in] air_temperature The air temperature in degrees C
[in] delta_t The temperature difference between the leaf and air in degrees C
[in] stomcond The stomatal conductance in m / s
[in] water_vapor_pressure The partial pressure of water vapor in the atmosphere in Pa
[in] minimum_gbw The lowest possible value for boundary layer conductance in m / s that should be returned
Returns
The boundary layer conductance in m / s
Definition at line 824 of file AuxBioCro.cpp.
References saturation_vapor_pressure().
leaf_boundary_layer_conductance_thornley()
double leaf_boundary_layer_conductance_thornley (double CanopyHeight, double WindSpeed, double minimum_gbw, double WindSpeedHeight)
Caluclates the conductance for water vapor flow between the leaf surface and the atmosphere (AKA, the boundary layer conductance) using a model described in Thornley and Johnson (1990).
This model considers gas flow due to wind-driven eddy currents. Here, the conductance is calculated using Equation 14.9 from pages 414 - 416 of the Thornley textbook. Unfortunately, an electronic version of this reference is not available.
In this model, the minimum possible boundary layer conductance that could occur is zero, which would correspond to zero wind speed or canopy height. In realistic field conditions, boundary layer conductance can never truly be zero. To accomodate this, an option is provided for setting a minimum value for the boundary layer counductance.
This model contains two singularities, which occur when either of the following conditions are met:
WindSpeedHeight + Zeta - d = 0, which is equivalent to CanopyHeight = WindSpeedHeight / (dCoef - ZetaCoef) = WindSpeedHeight * 1.34
WindSpeedHeight + ZetaM - d = 0, which is equivalent to CanopyHeight = WindSpeedHeight / (dCoef - ZetaMCoef) = WindSpeedHeight * 1.56
So, as the canopy height approaches or exceeds the height at which wind speed was measured, the calculated boundary layer conductance becomes unbounded. For even larger canopy heights, the conductance eventually begins to decrease. For tall crops, this is a severe limitation to this model. Here we address this issue by limiting the canopy height to 0.98 * WindSpeedHeight.
References:
Thornley, J. H. M. & Johnson, I. R. "Plant and Crop Modelling: A Mathematical Approach to Plant and Crop Physiology" (1990)
Parameters
[in] CanopyHeight The height of the canopy above the ground in m
[in] WindSpeed The wind speed in m / s as measured above the canopy at a reference height of five meters
[in] minimum_gbw The lowest possible value for boundary layer conductance in m / s that should be returned
[in] WindSpeedHeight The height in m at which the wind speed was measured
Returns
The boundary layer conductance in m / s
Definition at line 917 of file AuxBioCro.cpp.
Referenced by c3EvapoTrans().
LNprof()
void LNprof (double LeafN, double LAI, int nlayers, double kpLN, double * leafNla)
Definition at line 457 of file AuxBioCro.cpp.
Referenced by c3CanAC(), CanAC(), and multilayer_canopy_properties::run().
rootDist()
struct rd_str rootDist (int layer, double rootDepth, double * depths, double rfl)
Definition at line 1425 of file AuxBioCro.cpp.
saturation_vapor_pressure()
double saturation_vapor_pressure (double air_temperature)
Determine saturation water vapor pressure (Pa) from air temperature (degrees C) using the Arden Buck equation.
Equations of this form were used by Arden Buck to model saturation water vapor pressure in 1981: A. L. Buck, J. Appl. Meteor. 20, 1527–1532 (1981)
In 1996, some of the fitting coefficients were updated. Here we use these values, found in a Buck hygrometer manual, and also displayed on the Wikipedia page for the Arden Buck equation.
We use the values for vapor over water (rather than ice) and disregard the "enhancement factor" since we are only concerned with the pressure at saturation.
Parameters
[in] air_temperature Air temperature in degrees C
Returns
Saturation water vapor pressure in Pa
Definition at line 631 of file AuxBioCro.cpp.
Referenced by c3EvapoTrans(), leaf_boundary_layer_conductance_nikolov(), and SoilEvapo().
seqRootDepth()
struct seqRD_str seqRootDepth (double to, int lengthOut)
Definition at line 1425 of file AuxBioCro.cpp.
TempToDdryA()
double TempToDdryA (double air_temperature)
Determines the density of dry air from the air temperature.
This function appears to be derived from fitting a linear equation to the values of rho in Table 14.3 on pg. 408 in Thornley and Johnson (1990):
T (degrees C) rho (kg / m^3)
0 1.29
5 1.27
10 1.25
15 1.23
20 1.20
25 1.18
30 1.16
35 1.15
40 1.13
Thornley, J.H.M. and Johnson, I.R. (1990) Plant and Crop Modelling. A Mathematical Approach to Plant and Crop Physiology.
Parameters
[in] air_temperature Air temperature in degrees C
Returns
Density of dry air in kg / m^3
Definition at line 492 of file AuxBioCro.cpp.
Referenced by c3EvapoTrans(), and SoilEvapo().
TempToLHV()
double TempToLHV (double temperature)
Determine the latent heat of vaporization for water from its temperature.
This function appears to be derived from fitting a linear equation to the values of lambda in Table 14.3 on pg. 408 in Thornley and Johnson (1990):
T (degrees C) lambda (J / kg)
0 2.50
5 2.49
10 2.48
15 2.47
20 2.45
25 2.44
30 2.43
35 2.42
40 2.41
Thornley, J.H.M. and Johnson, I.R. (1990) Plant and Crop Modelling. A Mathematical Approach to Plant and Crop Physiology.
Parameters
[in] temperature Water temperature in degrees C
Returns
Latent heat of vaporization for water in J / kg
Definition at line 548 of file AuxBioCro.cpp.
Referenced by c3EvapoTrans(), and SoilEvapo().
TempToSFS()
double TempToSFS (double air_temperature)
Determine the derivative of saturation water vapor pressure with respect to temperature at a particular value of air temperature.
This function appears to be derived from fitting a quadratic function to the values of s in Table 14.3 on pg. 408 in Thornley and Johnson (1990):
T (degrees C) s (10^(-3) kg / m^3 / K)
0 0.33
5 0.45
10 0.60
15 0.78
20 1.01
25 1.30
30 1.65
35 2.07
40 2.57
Thornley, J.H.M. and Johnson, I.R. (1990) Plant and Crop Modelling. A Mathematical Approach to Plant and Crop Physiology.
Parameters
[in] air_temperature Air temperature in degrees C
Returns
Derivative of saturation water vapor pressure with respect to temperature in kg / m^3 / K (equivalent to Pa / K)
Definition at line 601 of file AuxBioCro.cpp.
Referenced by c3EvapoTrans(), and SoilEvapo().
Variable Documentation
soil_parameters
const std::map<SoilType, soilText_str> soil_parameters
Initial value:
=
{
  { SoilType::sand,            { 0.05, 0.03, 0.92,      -0.7,  1.7,  5.8e-3,      0.87, 0.09,  0.03, 1.60 } },
  { SoilType::loamy_sand,      { 0.12, 0.07, 0.81,      -0.9,  2.1,  1.7e-3,      0.72, 0.13,  0.06, 1.55 } },
  { SoilType::sandy_loam,      { 0.25, 0.10, 0.65,      -1.5,  3.1,  7.2e-4,      0.57, 0.21,  0.10, 1.50 } },
  { SoilType::loam,            { 0.40, 0.18, 0.42,      -1.1,  4.5,  3.7e-4,      0.57, 0.27,  0.12, 1.43 } },
  { SoilType::silt_loam,       { 0.65, 0.15, 0.20,      -2.1,  4.7,  1.9e-4,      0.59, 0.33,  0.13, 1.36 } },
  { SoilType::sandy_clay_loam, { 0.13, 0.27, 0.60,      -2.8,  4.0,  1.2e-4,      0.48, 0.26,  0.15, 1.39 } },
  { SoilType::clay_loam,       { 0.34, 0.34, 0.32,      -2.6,  5.2,  6.4e-5,      0.52, 0.32,  0.20, 1.35 } },
  { SoilType::silty_clay_loam, { 0.58, 0.33, 0.09,      -3.3,  6.6,  4.2e-5,      0.52, 0.37,  0.21, 1.24 } },
  { SoilType::sandy_clay,      { 0.07, 0.40, 0.53,      -2.9,  6.0,  3.3e-5,      0.51, 0.34,  0.24, 1.30 } },
  { SoilType::silty_clay,      { 0.45, 0.45, 0.10,      -3.4,  7.9,  2.5e-5,      0.52, 0.39,  0.25, 1.28 } },
  { SoilType::clay,            { 0.20, 0.60, 0.20,      -3.7,  7.6,  1.7e-5,      0.53, 0.40,  0.27, 1.19 } }
}
Definition at line 109 of file AuxBioCro.h.
Referenced by get_soil_properties().