The BioCro C++ Library: /github/workspace/src/module_library/AuxBioCro.cpp File Reference
AuxBioCro.cpp File Reference
#include <stdexcept>
#include <string>
#include <cmath>
#include "c4photo.h"
#include "BioCro.h"
#include "../constants.h"
Functions
double poisson_density (int x, double lambda)
Light_model lightME (double cosine_zenith_angle, double atmospheric_pressure)
Calculates some properties of the "light macro environment," i.e., the light just above the top of the canopy.
double absorbed_shortwave_from_incident_ppfd (double incident_ppfd, double par_energy_content, double par_energy_fraction, double leaf_reflectance, double leaf_transmittance)
Computes total absorbed shortwave radiation from the photosynthetically active photon flux density (PPFD) incident on a leaf.
Light_profile sunML (double ambient_ppfd_beam, double ambient_ppfd_diffuse, double lai, int nlayers, double cosine_zenith_angle, double kd, double chil, double absorptivity, double heightf, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance)
Computes an n-layered light profile from the direct light, diffuse light, leaf area index, solar zenith angle, and other parameters.
void WINDprof (double WindSpeed, double LAI, int nlayers, double *wind_speed_profile)
Wind profile function.
void RHprof (double RH, int nlayers, double *relative_humidity_profile)
Calculates a relative humidity profile throughout a multilayer canopy.
void LNprof (double LeafN, double LAI, int nlayers, double kpLN, double *leafN_profile)
double TempToDdryA (double air_temperature)
Determines the density of dry air from the air temperature.
double dry_air_density (const double air_temperature, const double air_pressure)
Calculate the density of dry air from temperature and pressure using the ideal gas law.
double TempToLHV (double temperature)
Determine the latent heat of vaporization for water from its temperature.
double water_latent_heat_of_vaporization_henderson (double temperature)
Determine the latent heat of vaporization of water from its temperature.
double TempToSFS (double air_temperature)
Determine the derivative of saturation water vapor pressure with respect to temperature at a particular value of air temperature.
double saturation_vapor_pressure (double air_temperature)
Determine saturation water vapor pressure (Pa) from air temperature (degrees C) using the Arden Buck equation.
struct ET_Str EvapoTrans2 (double absorbed_shortwave_radiation_et, double absorbed_shortwave_radiation_lt, double airTemp, double RH, double WindSpeed, double stomatal_conductance, double leaf_width, double specific_heat_of_air, double minimum_gbw, int eteq)
double leaf_boundary_layer_conductance_nikolov (double windspeed, double leafwidth, double air_temperature, double delta_t, double stomcond, double water_vapor_pressure, double minimum_gbw)
Caluclates the conductance for water vapor flow between the leaf surface and the atmosphere (AKA, the boundary layer conductance) using a model described in Nikolov, Massman, and Schoettle (1995).
double leaf_boundary_layer_conductance_thornley (double CanopyHeight, double WindSpeed, double minimum_gbw, double WindSpeedHeight)
Caluclates the conductance for water vapor flow between the leaf surface and the atmosphere (AKA, the boundary layer conductance) using a model described in Thornley and Johnson (1990).
double SoilEvapo (double LAI, double k, double air_temperature, double ppfd, double soil_water_content, double fieldc, double wiltp, double winds, double RelH, double rsec, double soil_clod_size, double soil_reflectance, double soil_transmission, double specific_heat_of_air, double par_energy_content)
double compute_wsPhoto (int wsFun, double fieldc, double wiltp, double phi1, double awc)
struct ws_str watstr (double precipit, double evapo, double cws, double soildepth, double fieldc, double wiltp, double soil_saturation_capacity, double sand, double Ks, double air_entry, double b)
struct soilML_str soilML (double precipit, double transp, double *cws, double soildepth, double *depths, double soil_field_capacity, double soil_wilting_point, double soil_saturation_capacity, double soil_air_entry, double soil_saturated_conductivity, double soil_b_coefficient, double soil_sand_content, double phi1, double phi2, int wsFun, int layers, double rootDB, double LAI, double k, double AirTemp, double IRad, double winds, double RelH, int hydrDist, double rfl, double rsec, double rsdf, double soil_clod_size, double soil_reflectance, double soil_transmission, double specific_heat_of_air, double par_energy_content)
double resp (double base_rate, double mrc, double temp)
Subtracts respiratory losses from a carbon production rate.
struct seqRD_str seqRootDepth (double to, int lengthOut)
struct rd_str rootDist (int n_layers, double rootDepth, double *depths, double rfl)
soilText_str get_soil_properties (int soiltype)
const soilText_str get_soil_properties (SoilType soiltype)
Function Documentation
absorbed_shortwave_from_incident_ppfd()
double absorbed_shortwave_from_incident_ppfd (double incident_ppfd, double par_energy_content, double par_energy_fraction, double leaf_reflectance, double leaf_transmittance)
Computes total absorbed shortwave radiation from the photosynthetically active photon flux density (PPFD) incident on a leaf.
Parameters
[in] incident_ppfd Photosynthetically active photon flux density (PPFD) incident on a leaf expressed in micromol / m^2 / s
[in] par_energy_content The energy content of PPFD expressed in J / micromol
[in] par_energy_fraction The fraction of total shortwave energy contained in the PAR band expressed as a real number between 0 and 1
[in] leaf_reflectance The fractional amount of shortwave radiation reflected by the leaf (weighted across all shortwave radiation)
[in] leaf_transmittance The fractional amount of shortwave radiation transmitted through the leaf (weighted across all shortwave radiation)
Returns
The total shortwave radiation absorbed by the leaf expressed in J / m^2 / s
The total absorbed shortwave radiation is determined using the following steps:
determine the incident photosynthetically active radiation (PAR) using the energy content of PAR
determine the incident near-infrared radiation (NIR) from the incident PAR using the PAR energy fraction
determine the total incident radiation by adding the incident PAR and NIR
determine the total absorbed radiation using the leaf's reflection and transmission coefficients
Definition at line 120 of file AuxBioCro.cpp.
Referenced by sunML().
compute_wsPhoto()
double compute_wsPhoto (int wsFun, double fieldc, double wiltp, double phi1, double awc)
Definition at line 1030 of file AuxBioCro.cpp.
dry_air_density()
double dry_air_density (const double air_temperature, const double air_pressure)
Calculate the density of dry air from temperature and pressure using the ideal gas law.
See https://en.wikipedia.org/wiki/Density_of_air for details.
Parameters
[in] air_temperature Air temperature in kelvin
[in] air_pressure Air pressure in Pa
Returns
Density of dry air in kg / m^3
Definition at line 511 of file AuxBioCro.cpp.
References physical_constants::ideal_gas_constant, and physical_constants::molar_mass_of_dry_air.
EvapoTrans2()
struct ET_Str EvapoTrans2 (double absorbed_shortwave_radiation_et, double absorbed_shortwave_radiation_lt, double airTemp, double RH, double WindSpeed, double stomatal_conductance, double leaf_width, double specific_heat_of_air, double minimum_gbw, int eteq)
Definition at line 631 of file AuxBioCro.cpp.
Referenced by CanAC(), and c4_leaf_photosynthesis::do_operation().
get_soil_properties() [1/2]
soilText_str get_soil_properties (int soiltype)
Definition at line 1493 of file AuxBioCro.cpp.
Referenced by soil_type_selector::do_operation().
get_soil_properties() [2/2]
const soilText_str get_soil_properties (SoilType soiltype)
Definition at line 1497 of file AuxBioCro.cpp.
References soil_parameters.
leaf_boundary_layer_conductance_nikolov()
double leaf_boundary_layer_conductance_nikolov (double windspeed, double leafwidth, double air_temperature, double delta_t, double stomcond, double water_vapor_pressure, double minimum_gbw)
Caluclates the conductance for water vapor flow between the leaf surface and the atmosphere (AKA, the boundary layer conductance) using a model described in Nikolov, Massman, and Schoettle (1995).
In this model, two types of gas flow are considered: "forced" flow driven by wind-created eddy currents and "free" flow driven by temperature-related buoyancy effects. The overall conductance is determined to be the larger of the free and forced conductances.
In this function, we use equations 29, 33, 34, and 35 to calculate boundary layer conductance. This is the same approach taken in the MLcan model of Drewry et al. (2010).
In this model, the minimum possible boundary layer conductance that could occur is zero. This would happen if wind speed is zero and the air and leaf temperatures are the same. In realistic field conditions, boundary layer conductance can never truly be zero. To accomodate this, an option is provided for setting a minimum value for the boundary layer counductance.
References:
Nikolov, N. T., Massman, W. J. & Schoettle, A. W. "Coupling biochemical and biophysical processes at the leaf level: an equilibrium photosynthesis model for leaves of C3 plants" Ecological Modelling 80, 205–235 (1995)
Drewry, D. T. et al. "Ecohydrological responses of dense canopies to environmental variability: 1. Interplay between vertical structure and photosynthetic pathway" Journal of Geophysical Research: Biogeosciences 115, (2010)
Parameters
[in] windspeed The wind speed in m / s
[in] leafwidth The characteristic leaf dimension in m
[in] air_temperature The air temperature in degrees C
[in] delta_t The temperature difference between the leaf and air in degrees C
[in] stomcond The stomatal conductance in m / s
[in] water_vapor_pressure The partial pressure of water vapor in the atmosphere in Pa
[in] minimum_gbw The lowest possible value for boundary layer conductance in m / s that should be returned
Returns
The boundary layer conductance in m / s
Definition at line 824 of file AuxBioCro.cpp.
References physical_constants::atmospheric_pressure_at_sea_level, conversion_constants::celsius_to_kelvin, and saturation_vapor_pressure().
Referenced by leaf_gbw_nikolov::do_operation().
leaf_boundary_layer_conductance_thornley()
double leaf_boundary_layer_conductance_thornley (double CanopyHeight, double WindSpeed, double minimum_gbw, double WindSpeedHeight)
Caluclates the conductance for water vapor flow between the leaf surface and the atmosphere (AKA, the boundary layer conductance) using a model described in Thornley and Johnson (1990).
This model considers gas flow due to wind-driven eddy currents. Here, the conductance is calculated using Equation 14.9 from pages 414 - 416 of the Thornley textbook. Unfortunately, an electronic version of this reference is not available.
In this model, the minimum possible boundary layer conductance that could occur is zero, which would correspond to zero wind speed or canopy height. In realistic field conditions, boundary layer conductance can never truly be zero. To accomodate this, an option is provided for setting a minimum value for the boundary layer counductance.
This model contains two singularities, which occur when either of the following conditions are met:
WindSpeedHeight + Zeta - d = 0, which is equivalent to CanopyHeight = WindSpeedHeight / (dCoef - ZetaCoef) = WindSpeedHeight * 1.34
WindSpeedHeight + ZetaM - d = 0, which is equivalent to CanopyHeight = WindSpeedHeight / (dCoef - ZetaMCoef) = WindSpeedHeight * 1.56
So, as the canopy height approaches or exceeds the height at which wind speed was measured, the calculated boundary layer conductance becomes unbounded. For even larger canopy heights, the conductance eventually begins to decrease. For tall crops, this is a severe limitation to this model. Here we address this issue by limiting the canopy height to 0.98 * WindSpeedHeight.
References:
Thornley, J. H. M. & Johnson, I. R. "Plant and Crop Modelling: A Mathematical Approach to Plant and Crop Physiology" (1990)
Parameters
[in] CanopyHeight The height of the canopy above the ground in m
[in] WindSpeed The wind speed in m / s as measured above the canopy at a reference height of five meters
[in] minimum_gbw The lowest possible value for boundary layer conductance in m / s that should be returned
[in] WindSpeedHeight The height in m at which the wind speed was measured
Returns
The boundary layer conductance in m / s
Definition at line 917 of file AuxBioCro.cpp.
Referenced by c3EvapoTrans(), and leaf_gbw_thornley::do_operation().
lightME()
Light_model lightME (double cosine_zenith_angle, double atmospheric_pressure)
Calculates some properties of the "light macro environment," i.e., the light just above the top of the canopy.
Parameters
[in] cosine_zenith_angle The cosine of the solar zenith angle; when the Sun is directly overhead, the angle is 0 and its cosine is 1; when the Sun is at the horizon, the angle is 90 and its cosine is 0
[in] atmospheric_pressure Local atmospheric pressure (in Pa)
The return value from this function is a customized structure (light_model) with the following members:
light_model.direct_irradiance_fraction: The fraction of irradiance that is direct radiation (dimensionless)
light_model.diffuse_irradiance_fraction: The fraction of irradiance that is diffuse radiation (dimensionless)
The basis for this function is given in chapter 11 of Norman and Campbell, An Introduction to Environmental Biophysics, 2nd edition.
Definition at line 62 of file AuxBioCro.cpp.
References physical_constants::atmospheric_pressure_at_sea_level, Light_model::diffuse_irradiance_fraction, and Light_model::direct_irradiance_fraction.
Referenced by c3CanAC(), and CanAC().
LNprof()
void LNprof (double LeafN, double LAI, int nlayers, double kpLN, double * leafN_profile)
Definition at line 457 of file AuxBioCro.cpp.
Referenced by c3CanAC(), CanAC(), and multilayer_canopy_properties::run().
poisson_density()
double poisson_density (int x, double lambda)
Definition at line 25 of file AuxBioCro.cpp.
resp()
double resp (double base_rate, double mrc, double temp)
Subtracts respiratory losses from a carbon production rate.
Parameters
[in] base_rate The base rate of carbon production that does not include respiratory losses. Any units are acceptable, e.g. mol / m^2 / s or Mg / ha / hour.
[in] mrc Maintenance respiration coefficient (dimensionless)
[in] temp Temperature (degrees C)
Returns
A modified rate having the same units as base_rate where respiratory losses have been subtracted
Model overview
The idea here is that the net carbon assimilation rate (A_n) is given by
A_n = A_g - R (1)
where A_g is the gross assimilation rate or the production rate and R is the respiration rate. A further assumption is that respiration is proportional to production, i.e.
R = R_c * A_g (2)
where R_c is a dimensionless coefficient that lies on the interval [0,1]. Combining equations (1) and (2), we can express the net assimilation rate as a function of the gross assimilation rate and the respiration coefficient:
A_n = A_g - R_c * A_g = A_g * (1 - R_c) (3)
In this function, the temperature dependence of the respiration coefficient is modeled using a simple "Q10" method where Q10 = 2 and the base temperature is 0 degrees C, i.e.,
R_c = R_c_0 * 2^(T / 10) (4)
where T is the temperature in Celsius. Combining equations (3) and (4), we finally arrive at a relationship between net assimilation, gross assimilation, and temperature:
A_n = A_g * (1 - R_c_0 * 2^(T / 10)) (5)
In the code below, base_rate represents the gross assimilation rate A_g, mrc represents the maintenance respiration coefficient R_c_0, and temp represents the temperature T.
Sources
In Stephen Humphries's thesis, he describes the respiration model in the following way: "The respiration model of McCree (1970) modified according to Penning de Vries (1972) and Thornley (1970) is used here to predict plant respiration... The respiration associated with each plant structure is modified according to the temperature of the structure using a Q10 approximation with a value of 2 as described by Spain and Keen (1992)."
I (EBL) believe these references to be to the following documents:
de Vries, F. P. "Respiration and growth" in "Crop processes in controlled environments" 327–347 (Academic Press, 1972)
Thornley, J. H. M. "Respiration, Growth and Maintenance in Plants" Nature 227, 304–305 (1970)
McCree, K. "An equation for the rate of respiration of whiteclover plants grown under controlled conditions" in: "Prediction and measurement of photosynthetic productivity" Wageningen: Centre for Agricultural Publishing and Documentation, 221-229 (1970)
Keen, R. E. & Spain, J. D. "Computer simulation in biology. A BASIC introduction" (1992)
I believe the McCree, Thornley, and de Vries papers describe the relationship between gross assimilation and respiration, while the Keen & Spain book describes the temperature dependence. Unfortunately, I can't find an online version of that book so I can't be sure.
For some general discussions about respiration, see the following two sources:
Amthor, J. S. "The McCree–de Wit–Penning de Vries–Thornley Respiration Paradigms: 30 Years Later" Ann Bot 86, 1–20 (2000)
Amthor, J. S. "The role of maintenance respiration in plant growth." Plant, Cell & Environment 7, 561–569 (1984)
The Humphries thesis is also unfortunately not available online:
Humphries, S. "Will mechanistically rich models provide us with new insights into the response of plant production to climate change?: development and experiments with WIMOVAC: (Windows Intuitive Model of Vegetation response to Atmosphere & Climate Change)" (University of Essex, 2002)
Definition at line 1425 of file AuxBioCro.cpp.
Referenced by no_leaf_resp_partitioning_growth_calculator::do_operation(), partitioning_growth_calculator::do_operation(), and no_leaf_resp_neg_assim_partitioning_growth_calculator::do_operation().
RHprof()
void RHprof (double RH, int nlayers, double * relative_humidity_profile)
Calculates a relative humidity profile throughout a multilayer canopy.
Parameters
[in] RH relative humidity just above the canopy (0 <= RH <= 1)
[in] nlayers number of layers in the canopy (1 <= nlayers <= MAXLAY)
[out] relative_humidity_profile array of relative humidity values expressed as fractions between 0 and 1, where the value at index i represents relative humidity at the bottom of canopy layer i and i = 0 corresponds to the top canopy layer.
One can derive an expression for the relative humidity (h) throughout a plant canopy by making the following assumptions:
h at the top of the canopy is the same as the ambient value (h = h0)
h at the bottom of the canopy is one hundred percent (h = 1)
h follows an exponential profile throughout the canopy
To enforce the exponential profile, we can write
h(x) = A * exp(B * x) [Equation (1)]
where x is a normalized expression of depth within the canopy (x = 0 at the canopy top and x = 1 at the bottom) and the values of A and B are yet to be determined.
To enforce the h value at the canopy top, we require h0 = h(0) = A; in other words, A = h0. To enforce the h value at the canopy bottom, we require 1 = h(1) = h0 * exp(B); in other words, B = -ln(h0). Putting it all together, we see that under these assumptions, h throughout the canopy is given by
h(x) = h0 * exp(-ln(h0) * x) [Equation (2)]
If we additionally assume that h0 is close to 1, we can simplify B = -ln(h0) by taking just the linear part of the Taylor series for -ln(h0) centered at h0 = 1, which is B = -(h0 - 1). With this modification, we have
h(x) = h0 * exp((1 - h0) * x) [Equation (3)]
When h0 = 1, Equations (2) and (3) are in perfect agreement, reducing to h(x) = 1. However, as h0 deviates further from h0 = 1, the linearization for B becomes less accurate and the two versions diverge, especially deeper in the canopy. For example, when h0 = 0.7, Equation (2) becomes h(x) = 0.7 * exp(0.357 * x) while Equation (3) becomes h(x) = 0.7 * exp(0.300 * x). Both versions agree at the top of the canopy where x = 0 and h(x) = 1, but are different at the bottom: 1.00 vs. 0.94. For lower h0 values, the difference at the canopy bottom becomes even more pronounced, significantly violating one of the original assumptions. However, there isn't a strong scientific justification for assuming humidity is 1 at the bottom of every canopy, so the error due to the approximation for B is deemed to be acceptable.
In BioCro, we divide the canopy into equally sized layers; i.e., the interval 0 <= x <= 1 is divided into n segments of length 1 / n by n + 1 boundaries occurring at x = 0, x = 1 / n, x = 2 / n, ..., x = 1. Here we wish to find the h value at the bottom of each layer, so we use Equation (3) with x = 1 / n, x = 2 / n, ..., x = 1.
In the code below, the RH input argument corresponds to h0, the exponential growth constant kh corresponds to B, and nlayers corresponds to n.
Note 1: the explanation for this code was "reverse engineered" by EBL from some crytpic documentation found in earlier versions of this function and from Stephen Humphries's thesis, which is not available online:
Humphries, S. "Will mechanistically rich models provide us with new insights into the response of plant production to climate change?: development and experiments with WIMOVAC: (Windows Intuitive Model of Vegetation response to Atmosphere & Climate Change)" (University of Essex, 2002).
Note 2: Equation (2) can be rewritten by noting that h0 = exp(ln(h0)). With this replacement, the equation becomes
h(x) = exp(ln(h0) - ln(h0) * x) = exp(-B * (1 - x))
The equation takes this form in Humphries's thesis.
Definition at line 438 of file AuxBioCro.cpp.
References MAXLAY.
Referenced by c3CanAC(), CanAC(), and multilayer_canopy_properties::run().
rootDist()
struct rd_str rootDist (int n_layers, double rootDepth, double * depths, double rfl)
Definition at line 1425 of file AuxBioCro.cpp.
saturation_vapor_pressure()
double saturation_vapor_pressure (double air_temperature)
Determine saturation water vapor pressure (Pa) from air temperature (degrees C) using the Arden Buck equation.
Equations of this form were used by Arden Buck to model saturation water vapor pressure in 1981: A. L. Buck, J. Appl. Meteor. 20, 1527–1532 (1981)
In 1996, some of the fitting coefficients were updated. Here we use these values, found in a Buck hygrometer manual, and also displayed on the Wikipedia page for the Arden Buck equation.
We use the values for vapor over water (rather than ice) and disregard the "enhancement factor" since we are only concerned with the pressure at saturation.
Parameters
[in] air_temperature Air temperature in degrees C
Returns
Saturation water vapor pressure in Pa
Definition at line 631 of file AuxBioCro.cpp.
Referenced by c3EvapoTrans(), buck_swvp::do_operation(), leaf_gbw_nikolov::do_operation(), water_vapor_properties_from_air_temperature::do_operation(), leaf_boundary_layer_conductance_nikolov(), and SoilEvapo().
seqRootDepth()
struct seqRD_str seqRootDepth (double to, int lengthOut)
Definition at line 1425 of file AuxBioCro.cpp.
SoilEvapo()
double SoilEvapo (double LAI, double k, double air_temperature, double ppfd, double soil_water_content, double fieldc, double wiltp, double winds, double RelH, double rsec, double soil_clod_size, double soil_reflectance, double soil_transmission, double specific_heat_of_air, double par_energy_content)
Definition at line 960 of file AuxBioCro.cpp.
References conversion_constants::celsius_to_kelvin, saturation_vapor_pressure(), physical_constants::stefan_boltzmann, TempToDdryA(), TempToLHV(), and TempToSFS().
Referenced by soil_evaporation::do_operation().
soilML()
struct soilML_str soilML (double precipit, double transp, double * cws, double soildepth, double * depths, double soil_field_capacity, double soil_wilting_point, double soil_saturation_capacity, double soil_air_entry, double soil_saturated_conductivity, double soil_b_coefficient, double soil_sand_content, double phi1, double phi2, int wsFun, int layers, double rootDB, double LAI, double k, double AirTemp, double IRad, double winds, double RelH, int hydrDist, double rfl, double rsec, double rsdf, double soil_clod_size, double soil_reflectance, double soil_transmission, double specific_heat_of_air, double par_energy_content)
Definition at line 1030 of file AuxBioCro.cpp.
Referenced by two_layer_soil_profile::do_operation().
sunML()
Light_profile sunML (double ambient_ppfd_beam, double ambient_ppfd_diffuse, double lai, int nlayers, double cosine_zenith_angle, double kd, double chil, double absorptivity, double heightf, double par_energy_content, double par_energy_fraction, double leaf_transmittance, double leaf_reflectance)
Computes an n-layered light profile from the direct light, diffuse light, leaf area index, solar zenith angle, and other parameters.
Parameters
[in] ambient_ppfd_beam Photosynthetically active photon flux density (PPFD) for beam light passing through a surface perpendicular to the beam direction at the top of the canopy; this represents direct sunlight for a plant in a field (micromol / (m^2 beam) / s)
[in] ambient_ppfd_diffuse Photosynthetically active photon flux density (PPFD) for diffuse light at the top of the canopy; this represents diffuse light scattered out of the solar beam by the Earth's atmosphere for a plant in a field; as a diffuse flux density, this represents the flux through any surface (micromol / m^2 / s)
[in] lai Leaf area index (LAI) of the entire canopy, which represents the leaf area per unit of ground area (dimensionless from m^2 leaf / m^2 ground)
[in] nlayers Integer number of layers in the canopy
[in] cosine_zenith_angle Cosine of the solar zenith angle (dimensionless)
[in] kd Extinction coefficient for diffuse light (dimensionless)
[in] chil Ratio of average projected areas of canopy elements on horizontal surfaces; for a spherical leaf distribution, chil = 0; for a vertical leaf distribution, chil = 1; for a horizontal leaf distribution, chil approaches infinity (dimensionless from m^2 / m^2)
[in] absorptivity The leaf absorptivity on a quantum basis (dimensionless from mol / mol)
[in] heightf Leaf area density, i.e., LAI per height of canopy (m^-1 from m^2 leaf / m^2 ground / m height)
Returns
An n-layered light profile representing quantities within the canopy, including several photon flux densities and the relative fractions of shaded and sunlit leaves
Definition at line 185 of file AuxBioCro.cpp.
References absorbed_shortwave_from_incident_ppfd(), Light_profile::average_absorbed_shortwave, Light_profile::average_incident_ppfd, Light_profile::height, Light_profile::incident_ppfd_scattered, MAXLAY, Light_profile::shaded_absorbed_shortwave, Light_profile::shaded_fraction, Light_profile::shaded_incident_ppfd, Light_profile::sunlit_absorbed_shortwave, Light_profile::sunlit_fraction, and Light_profile::sunlit_incident_ppfd.
Referenced by c3CanAC(), CanAC(), and multilayer_canopy_properties::run().
TempToDdryA()
double TempToDdryA (double air_temperature)
Determines the density of dry air from the air temperature.
This function appears to be derived from fitting a linear equation to the values of rho in Table 14.3 on pg. 408 in Thornley and Johnson (1990):
T (degrees C) rho (kg / m^3)
0 1.29
5 1.27
10 1.25
15 1.23
20 1.20
25 1.18
30 1.16
35 1.15
40 1.13
Thornley, J.H.M. and Johnson, I.R. (1990) Plant and Crop Modelling. A Mathematical Approach to Plant and Crop Physiology.
Parameters
[in] air_temperature Air temperature in degrees C
Returns
Density of dry air in kg / m^3
Definition at line 492 of file AuxBioCro.cpp.
Referenced by c3EvapoTrans(), water_vapor_properties_from_air_temperature::do_operation(), and SoilEvapo().
TempToLHV()
double TempToLHV (double temperature)
Determine the latent heat of vaporization for water from its temperature.
This function appears to be derived from fitting a linear equation to the values of lambda in Table 14.3 on pg. 408 in Thornley and Johnson (1990):
T (degrees C) lambda (J / kg)
0 2.50
5 2.49
10 2.48
15 2.47
20 2.45
25 2.44
30 2.43
35 2.42
40 2.41
Thornley, J.H.M. and Johnson, I.R. (1990) Plant and Crop Modelling. A Mathematical Approach to Plant and Crop Physiology.
Parameters
[in] temperature Water temperature in degrees C
Returns
Latent heat of vaporization for water in J / kg
Definition at line 548 of file AuxBioCro.cpp.
Referenced by c3EvapoTrans(), water_vapor_properties_from_air_temperature::do_operation(), and SoilEvapo().
TempToSFS()
double TempToSFS (double air_temperature)
Determine the derivative of saturation water vapor pressure with respect to temperature at a particular value of air temperature.
This function appears to be derived from fitting a quadratic function to the values of s in Table 14.3 on pg. 408 in Thornley and Johnson (1990):
T (degrees C) s (10^(-3) kg / m^3 / K)
0 0.33
5 0.45
10 0.60
15 0.78
20 1.01
25 1.30
30 1.65
35 2.07
40 2.57
Thornley, J.H.M. and Johnson, I.R. (1990) Plant and Crop Modelling. A Mathematical Approach to Plant and Crop Physiology.
Parameters
[in] air_temperature Air temperature in degrees C
Returns
Derivative of saturation water vapor pressure with respect to temperature in kg / m^3 / K (equivalent to Pa / K)
Definition at line 601 of file AuxBioCro.cpp.
Referenced by c3EvapoTrans(), water_vapor_properties_from_air_temperature::do_operation(), and SoilEvapo().
water_latent_heat_of_vaporization_henderson()
double water_latent_heat_of_vaporization_henderson (double temperature)
Determine the latent heat of vaporization of water from its temperature.
Here we use Equation 8 from Henderson-Sellers, B. "A new formula for latent heat of vaporization of water as a function of temperature" Quarterly Journal of the Royal Meteorological Society 110, 1186–1190 (1984)
Parameters
[in] temperature Water temperature in kelvin
Returns
Latent heat of vaporization for water in J / kg
Definition at line 568 of file AuxBioCro.cpp.
watstr()
struct ws_str watstr (double precipit, double evapo, double cws, double soildepth, double fieldc, double wiltp, double soil_saturation_capacity, double sand, double Ks, double air_entry, double b)
Definition at line 1030 of file AuxBioCro.cpp.
Referenced by one_layer_soil_profile::do_operation().
WINDprof()
void WINDprof (double WindSpeed, double LAI, int nlayers, double * wind_speed_profile)
Wind profile function.
Preconditions: WindSpeed is non-negative. LAI is non-negative nlayers is at least 1 and at most MAXLAY. wind_speed_profile is an array of at least size nlayers.
Definition at line 337 of file AuxBioCro.cpp.
Referenced by c3CanAC(), CanAC(), and multilayer_canopy_properties::run().