The BioCro C++ Library: /github/workspace/src/R_run_biocro.cpp File Reference
R_run_biocro.cpp File Reference
#include <Rinternals.h>
#include <string>
#include <exception>
#include "state_map.h"
#include "biocro_simulation.h"
#include "R_helper_functions.h"
Functions
SEXP R_run_biocro (SEXP initial_values, SEXP parameters, SEXP drivers, SEXP direct_module_names, SEXP differential_module_names, SEXP solver_type, SEXP solver_output_step_size, SEXP solver_adaptive_rel_error_tol, SEXP solver_adaptive_abs_error_tol, SEXP solver_adaptive_max_steps, SEXP verbose)
Function Documentation
R_run_biocro()
SEXP R_run_biocro (SEXP initial_values, SEXP parameters, SEXP drivers, SEXP direct_module_names, SEXP differential_module_names, SEXP solver_type, SEXP solver_output_step_size, SEXP solver_adaptive_rel_error_tol, SEXP solver_adaptive_abs_error_tol, SEXP solver_adaptive_max_steps, SEXP verbose)
Definition at line 12 of file R_run_biocro.cpp.
References biocro_simulation::generate_report(), list_from_map(), make_vector(), map_from_list(), map_vector_from_list(), parameters, and biocro_simulation::run_simulation().