The BioCro C++ Library: ode_solver Class Reference
ode_solver Class Reference abstract
#include <ode_solver.h>
Public Member Functions
ode_solver (std::string ode_solver_name, bool should_check_euler_requirement, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps)
virtual ~ode_solver ()
state_vector_map integrate (std::shared_ptr< dynamical_system > sys)
std::string generate_info_report () const
std::string generate_integrate_report () const
Protected Member Functions
double get_output_step_size () const
double get_adaptive_rel_error_tol () const
double get_adaptive_abs_error_tol () const
int get_adaptive_max_steps () const
Private Member Functions
virtual state_vector_map do_integrate (std::shared_ptr< dynamical_system > sys)=0
virtual state_vector_map handle_euler_requirement (std::shared_ptr< dynamical_system > sys)
virtual std::string get_param_info () const =0
virtual std::string get_solution_info () const =0
Private Attributes
const std::string ode_solver_name
const bool should_check_euler_requirement
double output_step_size
double adaptive_rel_error_tol
double adaptive_abs_error_tol
int adaptive_max_steps
bool integrate_method_has_been_called = false
Detailed Description
Definition at line 12 of file ode_solver.h.
Constructor & Destructor Documentation
ode_solver()
ode_solver (std::string ode_solver_name, bool should_check_euler_requirement, double step_size, double rel_error_tolerance, double abs_error_tolerance, int max_steps) inline
Definition at line 15 of file ode_solver.h.
~ode_solver()
virtual ~ode_solver () inline virtual
Definition at line 31 of file ode_solver.h.
Member Function Documentation
do_integrate()
virtual state_vector_map do_integrate (std::shared_ptr< dynamical_system > sys) private pure virtual
Implemented in homemade_euler_ode_solver< state_type >, boost_ode_solver< state_type >, boost_ode_solver< boost::numeric::ublas::vector< double > >, and auto_ode_solver< state_type >.
Referenced by integrate().
generate_info_report()
std::string generate_info_report () const inline
Definition at line 35 of file ode_solver.h.
References get_param_info(), and ode_solver_name.
generate_integrate_report()
std::string generate_integrate_report () const inline
Definition at line 40 of file ode_solver.h.
References get_solution_info(), and integrate_method_has_been_called.
get_adaptive_abs_error_tol()
double get_adaptive_abs_error_tol () const inline protected
Definition at line 52 of file ode_solver.h.
References adaptive_abs_error_tol.
Referenced by boost_rsnbrk_ode_solver::do_boost_integrate(), boost_rkck54_ode_solver< state_type >::do_boost_integrate(), boost_rkck54_ode_solver< state_type >::get_boost_param_info(), and boost_rsnbrk_ode_solver::get_boost_param_info().
get_adaptive_max_steps()
int get_adaptive_max_steps () const inline protected
Definition at line 53 of file ode_solver.h.
References adaptive_max_steps.
Referenced by boost_rkck54_ode_solver< state_type >::get_boost_param_info(), and boost_rsnbrk_ode_solver::get_boost_param_info().
get_adaptive_rel_error_tol()
double get_adaptive_rel_error_tol () const inline protected
Definition at line 51 of file ode_solver.h.
References adaptive_rel_error_tol.
Referenced by boost_rsnbrk_ode_solver::do_boost_integrate(), boost_rkck54_ode_solver< state_type >::do_boost_integrate(), boost_rkck54_ode_solver< state_type >::get_boost_param_info(), and boost_rsnbrk_ode_solver::get_boost_param_info().
get_output_step_size()
double get_output_step_size () const inline protected
Definition at line 50 of file ode_solver.h.
References output_step_size.
Referenced by boost_ode_solver< state_type >::get_param_info().
get_param_info()
virtual std::string get_param_info () const private pure virtual
Implemented in homemade_euler_ode_solver< state_type >, boost_ode_solver< state_type >, boost_ode_solver< boost::numeric::ublas::vector< double > >, and auto_ode_solver< state_type >.
Referenced by generate_info_report().
get_solution_info()
virtual std::string get_solution_info () const private pure virtual
Implemented in homemade_euler_ode_solver< state_type >, boost_ode_solver< state_type >, boost_ode_solver< boost::numeric::ublas::vector< double > >, and auto_ode_solver< state_type >.
Referenced by generate_integrate_report().
handle_euler_requirement()
state_vector_map handle_euler_requirement (std::shared_ptr< dynamical_system > sys) inline private virtual
Reimplemented in auto_ode_solver< state_type >.
Definition at line 74 of file ode_solver.h.
References ode_solver_name.
Referenced by integrate().
integrate()
state_vector_map integrate (std::shared_ptr< dynamical_system > sys)
Definition at line 3 of file ode_solver.cpp.
References do_integrate(), handle_euler_requirement(), integrate_method_has_been_called, and should_check_euler_requirement.
Member Data Documentation
adaptive_abs_error_tol
double adaptive_abs_error_tol private
Definition at line 61 of file ode_solver.h.
Referenced by get_adaptive_abs_error_tol().
adaptive_max_steps
int adaptive_max_steps private
Definition at line 62 of file ode_solver.h.
Referenced by get_adaptive_max_steps().
adaptive_rel_error_tol
double adaptive_rel_error_tol private
Definition at line 60 of file ode_solver.h.
Referenced by get_adaptive_rel_error_tol().
integrate_method_has_been_called
bool integrate_method_has_been_called = false private
Definition at line 64 of file ode_solver.h.
Referenced by generate_integrate_report(), and integrate().
ode_solver_name
const std::string ode_solver_name private
Definition at line 56 of file ode_solver.h.
Referenced by generate_info_report(), and handle_euler_requirement().
output_step_size
double output_step_size private
Definition at line 59 of file ode_solver.h.
Referenced by get_output_step_size().
should_check_euler_requirement
const bool should_check_euler_requirement private
Definition at line 57 of file ode_solver.h.
Referenced by integrate().
The documentation for this class was generated from the following files:
/github/workspace/src/ode_solver.h
/github/workspace/src/ode_solver.cpp