The BioCro C++ Library: ten_layer_canopy_properties Class Reference
ten_layer_canopy_properties Class Reference
A child class of multilayer_canopy_properties where the number of layers has been defined. Instances of this class can be created using the module factory, unlike the parent class multilayer_canopy_properties.
#include <multilayer_canopy_properties.h>
Public Member Functions
ten_layer_canopy_properties (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from multilayer_canopy_properties
multilayer_canopy_properties (int const &nlayers, state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from direct_module
direct_module (bool requires_euler=false)
virtual ~direct_module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from module_base
module_base (bool const &differential, bool const &requires_euler)
virtual ~module_base ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
bool is_differential () const
bool requires_euler_ode_solver () const
void run () const
Static Public Member Functions
static string_vector get_inputs ()
static string_vector define_leaf_classes ()
static string_vector define_multiclass_multilayer_outputs ()
static string_vector define_pure_multilayer_outputs ()
static string_vector get_outputs ()
static std::string get_name ()
Private Member Functions
void do_operation () const
Static Private Attributes
static int const nlayers = 10
Additional Inherited Members
Protected Member Functions inherited from multilayer_canopy_properties
void run () const
Protected Member Functions inherited from direct_module
void update (double *output_ptr, const double &value) const
In a valid dynamical_system object, a given quantity may be defined by only one direct module. Thus the value at output_ptr will only be writable from a single module, and we can overwrite any previously stored value.
Static Protected Member Functions inherited from multilayer_canopy_properties
static string_vector get_inputs (int nlayers)
Define all inputs required by the module.
static string_vector define_leaf_classes ()
Define the different leaf classes included by the module.
static string_vector define_multiclass_multilayer_outputs ()
Define all outputs that have different values for each leaf class and layer.
static string_vector define_pure_multilayer_outputs ()
Define all outputs that have different values for each layer, not including outputs that also depend on leaf class.
static string_vector get_outputs (int nlayers)
Define all output names by appending leaf class prefixes and layer number suffixes. Here we should make use of the define_XXX functions to reduce code duplication.
Detailed Description
A child class of multilayer_canopy_properties where the number of layers has been defined. Instances of this class can be created using the module factory, unlike the parent class multilayer_canopy_properties.
Definition at line 159 of file multilayer_canopy_properties.h.
Constructor & Destructor Documentation
ten_layer_canopy_properties()
ten_layer_canopy_properties (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 162 of file multilayer_canopy_properties.h.
Member Function Documentation
define_leaf_classes()
string_vector define_leaf_classes () static
Definition at line 165 of file multilayer_canopy_properties.cpp.
References multilayer_canopy_properties::define_leaf_classes().
define_multiclass_multilayer_outputs()
string_vector define_multiclass_multilayer_outputs () static
Definition at line 170 of file multilayer_canopy_properties.cpp.
References multilayer_canopy_properties::define_multiclass_multilayer_outputs().
define_pure_multilayer_outputs()
string_vector define_pure_multilayer_outputs () static
Definition at line 176 of file multilayer_canopy_properties.cpp.
References multilayer_canopy_properties::define_pure_multilayer_outputs().
do_operation()
void do_operation () const private virtual
Implements module_base.
Definition at line 187 of file multilayer_canopy_properties.cpp.
References multilayer_canopy_properties::run().
get_inputs()
string_vector get_inputs () static
Definition at line 160 of file multilayer_canopy_properties.cpp.
References multilayer_canopy_properties::get_inputs(), and nlayers.
get_name()
static std::string get_name () inline static
Definition at line 176 of file multilayer_canopy_properties.h.
get_outputs()
string_vector get_outputs () static
Definition at line 182 of file multilayer_canopy_properties.cpp.
References multilayer_canopy_properties::get_outputs(), and nlayers.
Member Data Documentation
nlayers
int const nlayers = 10 static private
Definition at line 180 of file multilayer_canopy_properties.h.
Referenced by get_inputs(), and get_outputs().
The documentation for this class was generated from the following files:
/github/workspace/src/module_library/multilayer_canopy_properties.h
/github/workspace/src/module_library/multilayer_canopy_properties.cpp