The BioCro C++ Library: rh_to_mole_fraction Class Reference
rh_to_mole_fraction Class Reference
Converts atmospheric relative humidity into a water vapor concentration expressed as a dimensionless mole fraction.
#include <rh_to_mole_fraction.h>
Public Member Functions
rh_to_mole_fraction (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from direct_module
direct_module (bool requires_euler=false)
virtual ~direct_module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from module_base
module_base (bool const &differential, bool const &requires_euler)
virtual ~module_base ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
bool is_differential () const
bool requires_euler_ode_solver () const
void run () const
Static Public Member Functions
static string_vector get_inputs ()
static string_vector get_outputs ()
static std::string get_name ()
Private Member Functions
void do_operation () const
Private Attributes
double const & rh
double const & atmospheric_pressure
double const & saturation_water_vapor_pressure_atmosphere
double * mole_fraction_h2o_atmosphere_op
Additional Inherited Members
Protected Member Functions inherited from direct_module
void update (double *output_ptr, const double &value) const
In a valid dynamical_system object, a given quantity may be defined by only one direct module. Thus the value at output_ptr will only be writable from a single module, and we can overwrite any previously stored value.
Detailed Description
Converts atmospheric relative humidity into a water vapor concentration expressed as a dimensionless mole fraction.
Relative humidity (RH) is defined as the ratio of the partial pressure of water vapor in air (WVP) to the saturation water vapor pressure of the air (SWVP): RH = WVP / SWVP.
Molar water vapor concentration (XW) is defined as the number of moles of water vapor divided by the total number of moles of gas molecules in a mixture. For an ideal gas, it can be shown that this ratio is equivalent to the ratio of WVP to the total air pressure (AP): XW = WVP / AP.
Combining these two equations, it is possible to calculate XW from RH, SWVP, and AP: XW = RH * SWVP / AP.
For more info, see Campbell, G. S. & Norman, J. M. "Chapter 3: Water Vapor and Other Gases" in "An Introduction to Environmental Biophysics" (1998).
In BioCro and in the code below, these quantities are represented as follows:
'rh' for the local atmospheric relative humidity RH
'atmospheric_pressure' for the local atmospheric pressure AP
'saturation_water_vapor_pressure_atmosphere' for the saturation water vapor pressure in the local atmosphere SWVP
Definition at line 39 of file rh_to_mole_fraction.h.
Constructor & Destructor Documentation
rh_to_mole_fraction()
rh_to_mole_fraction (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 42 of file rh_to_mole_fraction.h.
Member Function Documentation
do_operation()
void do_operation () const private virtual
Implements module_base.
Definition at line 89 of file rh_to_mole_fraction.h.
References atmospheric_pressure, check_error_conditions(), calculation_constants::eps_zero, get_name(), mole_fraction_h2o_atmosphere_op, rh, saturation_water_vapor_pressure_atmosphere, and direct_module::update().
get_inputs()
string_vector get_inputs () static
Definition at line 73 of file rh_to_mole_fraction.h.
get_name()
static std::string get_name () inline static
Definition at line 58 of file rh_to_mole_fraction.h.
Referenced by do_operation().
get_outputs()
string_vector get_outputs () static
Definition at line 82 of file rh_to_mole_fraction.h.
Member Data Documentation
atmospheric_pressure
double const& atmospheric_pressure private
Definition at line 63 of file rh_to_mole_fraction.h.
Referenced by do_operation().
mole_fraction_h2o_atmosphere_op
double* mole_fraction_h2o_atmosphere_op private
Definition at line 67 of file rh_to_mole_fraction.h.
Referenced by do_operation().
rh
double const& rh private
Definition at line 62 of file rh_to_mole_fraction.h.
Referenced by do_operation().
saturation_water_vapor_pressure_atmosphere
double const& saturation_water_vapor_pressure_atmosphere private
Definition at line 64 of file rh_to_mole_fraction.h.
Referenced by do_operation().
The documentation for this class was generated from the following file:
/github/workspace/src/module_library/rh_to_mole_fraction.h