The BioCro C++ Library: water_vapor_properties_from_air_temperature Class Reference
water_vapor_properties_from_air_temperature Class Reference
#include <water_vapor_properties_from_air_temperature.hpp>
Public Member Functions
water_vapor_properties_from_air_temperature (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from direct_module
direct_module (bool requires_euler=false)
virtual ~direct_module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from module_base
module_base (bool const &differential, bool const &requires_euler)
virtual ~module_base ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
bool is_differential () const
bool requires_euler_ode_solver () const
void run () const
Static Public Member Functions
static string_vector get_inputs ()
static string_vector get_outputs ()
static std::string get_name ()
Private Member Functions
void do_operation () const
Private Attributes
double const & temp
double const & rh
double const & specific_heat_of_air
double * latent_heat_vaporization_of_water_op
double * slope_water_vapor_op
double * saturation_water_vapor_pressure_op
double * water_vapor_pressure_op
double * vapor_density_deficit_op
double * psychrometric_parameter_op
Additional Inherited Members
Protected Member Functions inherited from direct_module
void update (double *output_ptr, const double &value) const
In a valid dynamical_system object, a given quantity may be defined by only one direct module. Thus the value at output_ptr will only be writable from a single module, and we can overwrite any previously stored value.
Detailed Description
Definition at line 11 of file water_vapor_properties_from_air_temperature.hpp.
Constructor & Destructor Documentation
water_vapor_properties_from_air_temperature()
water_vapor_properties_from_air_temperature (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 14 of file water_vapor_properties_from_air_temperature.hpp.
Member Function Documentation
do_operation()
void do_operation () const private virtual
Implements module_base.
Definition at line 76 of file water_vapor_properties_from_air_temperature.hpp.
References conversion_constants::celsius_to_kelvin, physical_constants::ideal_gas_constant, latent_heat_vaporization_of_water_op, physical_constants::molar_mass_of_water, psychrometric_parameter_op, rh, saturation_vapor_pressure(), saturation_water_vapor_pressure_op, slope_water_vapor_op, specific_heat_of_air, temp, TempToDdryA(), TempToLHV(), TempToSFS(), direct_module::update(), vapor_density_deficit_op, and water_vapor_pressure_op.
get_inputs()
string_vector get_inputs () static
Definition at line 55 of file water_vapor_properties_from_air_temperature.hpp.
get_name()
static std::string get_name () inline static
Definition at line 35 of file water_vapor_properties_from_air_temperature.hpp.
get_outputs()
string_vector get_outputs () static
Definition at line 64 of file water_vapor_properties_from_air_temperature.hpp.
Member Data Documentation
latent_heat_vaporization_of_water_op
double* latent_heat_vaporization_of_water_op private
Definition at line 44 of file water_vapor_properties_from_air_temperature.hpp.
Referenced by do_operation().
psychrometric_parameter_op
double* psychrometric_parameter_op private
Definition at line 49 of file water_vapor_properties_from_air_temperature.hpp.
Referenced by do_operation().
rh
double const& rh private
Definition at line 40 of file water_vapor_properties_from_air_temperature.hpp.
Referenced by do_operation().
saturation_water_vapor_pressure_op
double* saturation_water_vapor_pressure_op private
Definition at line 46 of file water_vapor_properties_from_air_temperature.hpp.
Referenced by do_operation().
slope_water_vapor_op
double* slope_water_vapor_op private
Definition at line 45 of file water_vapor_properties_from_air_temperature.hpp.
Referenced by do_operation().
specific_heat_of_air
double const& specific_heat_of_air private
Definition at line 41 of file water_vapor_properties_from_air_temperature.hpp.
Referenced by do_operation().
temp
double const& temp private
Definition at line 39 of file water_vapor_properties_from_air_temperature.hpp.
Referenced by do_operation().
vapor_density_deficit_op
double* vapor_density_deficit_op private
Definition at line 48 of file water_vapor_properties_from_air_temperature.hpp.
Referenced by do_operation().
water_vapor_pressure_op
double* water_vapor_pressure_op private
Definition at line 47 of file water_vapor_properties_from_air_temperature.hpp.
Referenced by do_operation().
The documentation for this class was generated from the following file:
/github/workspace/src/module_library/water_vapor_properties_from_air_temperature.hpp