The BioCro C++ Library: /github/workspace/src/degree_trigonometry.h File Reference
degree_trigonometry.h File Reference
#include <cmath>
#include "constants.h"
Functions
template<typename T >
double sin_deg (T angle)
template<typename T >
double cos_deg (T angle)
template<typename T >
double tan_deg (T angle)
template<typename T >
double asin_deg (T arg)
template<typename T >
double acos_deg (T arg)
template<typename T >
double atan2_deg (T y, T x)
Function Documentation
acos_deg()
double acos_deg (T arg)
Definition at line 34 of file degree_trigonometry.h.
Referenced by solar_position_michalsky::do_operation().
asin_deg()
double asin_deg (T arg)
Definition at line 28 of file degree_trigonometry.h.
Referenced by solar_position_michalsky::do_operation().
atan2_deg()
double atan2_deg (T y, T x)
Definition at line 40 of file degree_trigonometry.h.
Referenced by solar_position_michalsky::do_operation().
cos_deg()
double cos_deg (T angle)
Definition at line 16 of file degree_trigonometry.h.
Referenced by solar_position_michalsky::do_operation().
sin_deg()
double sin_deg (T angle)
Definition at line 10 of file degree_trigonometry.h.
Referenced by solar_position_michalsky::do_operation().
tan_deg()
double tan_deg (T angle)
Definition at line 22 of file degree_trigonometry.h.