The BioCro C++ Library: /github/workspace/src/R_get_all.cpp File Reference
R_get_all.cpp File Reference
#include <Rinternals.h>
#include <vector>
#include <string>
#include "R_helper_functions.h"
#include "module_library/module_wrapper_factory.h"
#include "ode_solver_library/ode_solver_factory.h"
Functions
SEXP R_get_all_modules ()
SEXP R_get_all_quantities ()
SEXP R_get_all_ode_solvers ()
Function Documentation
R_get_all_modules()
SEXP R_get_all_modules ()
Definition at line 10 of file R_get_all.cpp.
References module_wrapper_factory::get_modules(), and r_string_vector_from_vector().
R_get_all_ode_solvers()
SEXP R_get_all_ode_solvers ()
Definition at line 34 of file R_get_all.cpp.
References ode_solver_factory::get_ode_solvers(), and r_string_vector_from_vector().
R_get_all_quantities()
SEXP R_get_all_quantities ()
Definition at line 22 of file R_get_all.cpp.
References module_wrapper_factory::get_all_quantities(), and list_from_map().