The BioCro C++ Library: ten_layer_canopy_integrator Class Reference
ten_layer_canopy_integrator Class Reference
A child class of multilayer_canopy_integrator where the number of layers has been defined. Instances of this class can be created using the module factory, unlike the parent class multilayer_canopy_integrator.
#include <multilayer_canopy_integrator.h>
Public Member Functions
ten_layer_canopy_integrator (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from multilayer_canopy_integrator
multilayer_canopy_integrator (int const &nlayers, state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from direct_module
direct_module (bool requires_euler=false)
virtual ~direct_module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from module_base
module_base (bool const &differential, bool const &requires_euler)
virtual ~module_base ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
bool is_differential () const
bool requires_euler_ode_solver () const
void run () const
Static Public Member Functions
static string_vector get_inputs ()
static string_vector get_leaf_classes ()
static string_vector get_multiclass_multilayer_outputs ()
static string_vector get_pure_multilayer_outputs ()
static string_vector get_outputs ()
static std::string get_name ()
Static Public Member Functions inherited from multilayer_canopy_integrator
static string_vector get_inputs (int nlayers)
Define all inputs required by the module, adding layer suffixes as required.
static string_vector get_outputs (int nlayers)
Define all outputs produced by the module.
Private Member Functions
void do_operation () const
Static Private Attributes
static int const nlayers = 10
Additional Inherited Members
Protected Member Functions inherited from multilayer_canopy_integrator
void run () const
Protected Member Functions inherited from direct_module
void update (double *output_ptr, const double &value) const
In a valid dynamical_system object, a given quantity may be defined by only one direct module. Thus the value at output_ptr will only be writable from a single module, and we can overwrite any previously stored value.
Detailed Description
A child class of multilayer_canopy_integrator where the number of layers has been defined. Instances of this class can be created using the module factory, unlike the parent class multilayer_canopy_integrator.
Definition at line 212 of file multilayer_canopy_integrator.h.
Constructor & Destructor Documentation
ten_layer_canopy_integrator()
ten_layer_canopy_integrator (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 215 of file multilayer_canopy_integrator.h.
Member Function Documentation
do_operation()
void do_operation () const private virtual
Reimplemented from multilayer_canopy_integrator.
Definition at line 253 of file multilayer_canopy_integrator.h.
References multilayer_canopy_integrator::run().
get_inputs()
string_vector get_inputs () static
Definition at line 241 of file multilayer_canopy_integrator.h.
References multilayer_canopy_integrator::get_inputs(), and nlayers.
get_leaf_classes()
static string_vector get_leaf_classes () static
get_multiclass_multilayer_outputs()
static string_vector get_multiclass_multilayer_outputs () static
get_name()
static std::string get_name () inline static
Definition at line 229 of file multilayer_canopy_integrator.h.
get_outputs()
string_vector get_outputs () static
Definition at line 247 of file multilayer_canopy_integrator.h.
References multilayer_canopy_integrator::get_outputs(), and nlayers.
get_pure_multilayer_outputs()
static string_vector get_pure_multilayer_outputs () static
Member Data Documentation
nlayers
int const nlayers = 10 static private
Definition at line 233 of file multilayer_canopy_integrator.h.
Referenced by get_inputs(), and get_outputs().
The documentation for this class was generated from the following file:
/github/workspace/src/module_library/multilayer_canopy_integrator.h